// Copyright 2026 Ye Zhou
// SPDX-License-Identifier: Apache-2.0

import { ARCHETYPES, CARDS, PATHS } from './content';
import { CATEGORY_NAMES, STATUS_NAMES } from './i18n';
import { RULES } from './rules';
import { STATUS_HELP } from './status-help';
import type { Path, Text } from './types';

const t = (en: string, zh: string, vi: string): Text => ({ en, 'zh-CN': zh, vi });
export interface KeywordEntry { id: string; name: Text; description: Text; paths: Path[]; }
export interface ArchetypeEntry { id: string; name: Text; description: Text; cardIds: string[]; }
export interface DaoEntry {
  id: Path; name: Text; description: Text; archetypes: ArchetypeEntry[];
  keywords: string[]; exampleCardIds: string[]; playPattern: Text; crossPath: Text;
}
const keyword = (id: string, name: Text, description: Text, paths: Path[] = []): KeywordEntry => ({ id, name, description, paths });
const statusPaths: Partial<Record<keyof typeof STATUS_NAMES, Path[]>> = {
  strength: ['strength', 'summoning'], fortify: ['earth'], pierce: ['metal'], protectiveQi: ['metal', 'earth'],
  swordIntent: ['sword'], tidalMomentum: ['water'], windMomentum: ['wind'], bleeding: ['blood'], flame: ['fire'],
  seed: ['wood'], regen: ['wood'], basicPower: ['strength'], basicCost: ['strength'],
};
/** One canonical keyword source for the encyclopedia, card help and searchable rules. */
export const KEYWORD_GLOSSARY: Record<string, KeywordEntry> = Object.fromEntries([
  ...Object.entries(STATUS_NAMES).map(([id, name]) => keyword(id, name, STATUS_HELP[id as keyof typeof STATUS_HELP], statusPaths[id as keyof typeof statusPaths] ?? [])),
  keyword('daoYuan', t('Dao Yuan', '道元', 'Đạo Nguyên'), t('Pays card costs. Refill at the start of your turn; ordinary unspent Yuan does not carry over. Some effects raise this combat’s maximum.', '用于支付卡牌费用。你的回合开始时恢复，普通剩余道元不跨回合保留。部分效果可提高本场战斗上限。', 'Dùng trả phí bài. Hồi đầy đầu lượt; Đạo Nguyên dư thông thường không chuyển sang lượt sau. Một số hiệu ứng tăng mức tối đa trong trận.'), ['water']),
  keyword('armor', t('Armor', '护甲', 'Giáp'), t('Absorbs external damage before HP is lost. Your remaining Armor is halved, rounded down, at the start of your next turn. Direct HP loss bypasses it.', '先于生命承受外部伤害。你的剩余护甲在下回合开始时减半，向下取整；直接失去生命不经过护甲。', 'Hấp thụ sát thương bên ngoài trước sinh lực. Giáp còn lại của bạn giảm một nửa, làm tròn xuống, ở đầu lượt tiếp theo. Mất sinh lực trực tiếp bỏ qua Giáp.'), ['earth', 'formation']),
  keyword('activeDiscard', t('Active Discard', '主动弃牌', 'Chủ Động Bỏ Bài'), t('Discard caused explicitly by a card or enemy effect. It triggers Hidden Schemes on-discard effects. Natural end-turn discard, overflow and top-deck filtering do not.', '由卡牌或敌方效果明确造成的弃牌，会触发暗谋的弃牌效果。自然回合结束弃牌、手牌溢出与牌库筛选均不触发。', 'Bỏ bài do hiệu ứng bài hoặc địch yêu cầu rõ ràng. Kích hiệu ứng khi bỏ của Ám Kế. Bỏ tự nhiên cuối lượt, tràn tay và lọc đầu Chồng Rút không kích hoạt.'), ['wisdom']),
  keyword('retain', t('Retain', '保留', 'Giữ Lại'), t('Keeps this card in hand through the natural end-turn discard. Each real retained turn can strengthen Formation effects. Playing or actively discarding it ends its preparation.', '自然回合结束弃牌时仍留在手中。每个实际保留的回合可强化阵道效果；打出或主动弃置后结束该次准备。', 'Giữ lá trên tay qua lần bỏ tự nhiên cuối lượt. Mỗi lượt thật sự giữ có thể tăng hiệu ứng Trận Đạo. Dùng hoặc chủ động bỏ sẽ kết thúc lần chuẩn bị ấy.'), ['formation']),
  keyword('exhaust', t('Exhaust', '消耗', 'Tiêu Hao'), t('Moves a combat card to the Exhaust pile. It will not join the normal reshuffle; recovery effects can still retrieve it. Your permanent deck is unchanged.', '将战斗牌移入消耗堆，不参与普通洗牌，但可被回收效果取回。不会改变永久牌组。', 'Chuyển bài chiến đấu vào Chồng Tiêu Hao, không tham gia xáo lại thông thường. Hiệu ứng thu hồi vẫn lấy lại được. Bộ bài vĩnh viễn không đổi.'), ['refinement']),
  keyword('refine', t('Re-Refinement', '重炼', 'Trọng Luyện'), t('Temporarily raises a card’s grade for this combat. It does not change the saved permanent grade. Status cards and Divine Abilities are ungraded.', '临时提高卡牌本场战斗的品阶，不改变永久品阶。状态牌与神通没有品阶。', 'Tạm tăng phẩm bài trong trận này, không đổi phẩm vĩnh viễn đã lưu. Bài Trạng Thái và Thần Thông không có phẩm.'), ['refinement']),
  keyword('intercept', t('Intercept', '拦截', 'Chặn Đòn'), t(`Up to ${RULES.summonSlots} living summons intercept ${RULES.interceptPercentEach}% each of incoming external damage to you. Direct HP loss bypasses Intercept.`, `至多${RULES.summonSlots}只存活召唤物各拦截你所受外部伤害的${RULES.interceptPercentEach}%。直接失去生命不触发拦截。`, `Tối đa ${RULES.summonSlots} vật triệu hồi còn sống, mỗi con chặn ${RULES.interceptPercentEach}% sát thương bên ngoài hướng vào bạn. Mất sinh lực trực tiếp bỏ qua Chặn Đòn.`), ['summoning', 'wood']),
  keyword('summon', t('Summon', '召唤物', 'Vật Triệu Hồi'), t('A separate ally with its own HP, attack and statuses. Its automatic trigger is turn end, counterattack or enemy Armor breaking. Commands use the summon’s own attack stats.', '具有独立生命、攻击和状态的友方单位，按自身类型在回合结束、反击或敌方破甲时行动。号令使用召唤物自身攻击属性。', 'Đồng minh riêng có sinh lực, công kích và trạng thái riêng. Tự hành động cuối lượt, khi phản kích hoặc khi Giáp địch vỡ tùy loại. Hiệu Lệnh dùng chỉ số công kích của chính nó.'), ['summoning', 'wood']),
  keyword('tidalDomain', t('Tidal Domain', '潮汐领域', 'Lĩnh Vực Thủy Triều'), t('Choose Rising Tide, Tranquil Sea or Raging Tide when awakened and at turn end. It acts only if at least 1 Dao Yuan remains; that Yuan is checked, not spent. A Domain uses no summon slot.', '唤醒时与回合结束时选择涨潮、静海或怒涛。仅在剩余至少1道元时发动；该道元只检查，不消耗。领域不占召唤位。', 'Chọn Triều Dâng, Biển Lặng hoặc Sóng Dữ khi thức tỉnh và cuối lượt. Chỉ phát động khi còn ít nhất 1 Đạo Nguyên; kiểm tra nhưng không tiêu số đó. Lĩnh vực không chiếm ô triệu hồi.'), ['water']),
  keyword('gale', t('Gale', '狂风', 'Cuồng Phong'), t(`Each ${RULES.galeThreshold} Wind Momentum triggers ${RULES.galeDamage} external damage to all enemies before Gale power bonuses. Gale is not an Attack and does not gain Strength or Sword Intent.`, `每${RULES.galeThreshold}层风势触发对全体敌人${RULES.galeDamage}点外部伤害，狂风持续能力可另行加成。狂风不是攻击，不受力量或剑意增伤。`, `Mỗi ${RULES.galeThreshold} Phong Thế kích ${RULES.galeDamage} sát thương bên ngoài lên mọi địch, trước phần tăng từ năng lực Cuồng Phong. Cuồng Phong không phải Tấn Công, không nhận Sức Mạnh hay Kiếm Ý.`), ['wind']),
  keyword('nextWindDiscount', t('Next Wind Discount', '下张风道减耗', 'Giảm Phí Phong Đạo Kế Tiếp'), t('Reduces the Dao Yuan cost of your next Wind card this turn, to a minimum of 0. Playing that card consumes the discount; an unused discount expires at turn end.', '降低本回合下一张风道牌的道元消耗，最低为0；打出该牌时消耗减免，回合结束时未用的减免失效。', 'Giảm phí Đạo Nguyên của lá Phong Đạo tiếp theo trong lượt, thấp nhất 0. Dùng lá đó sẽ tiêu phần giảm; nếu chưa dùng, phần giảm hết hiệu lực cuối lượt.'), ['wind']),
  keyword('lifesteal', t('Lifesteal', '汲血', 'Hút Sinh Lực'), t('Restores HP from actual HP damage dealt by the attack. Damage absorbed by Armor, negated or overkilled does not increase the healing.', '按攻击实际造成的生命损失回复；被护甲吸收、被抵消或超出剩余生命的伤害不增加回复量。', 'Hồi sinh lực theo sinh lực thực sự bị đòn đánh lấy đi. Sát thương bị Giáp hấp thụ, bị vô hiệu hoặc vượt sinh lực còn lại không tăng lượng hồi.'), ['blood']),
  keyword('directLoss', t('Direct HP Loss', '直接失去生命', 'Mất Sinh Lực Trực Tiếp'), t('A resource payment or explicitly direct loss. It bypasses Armor, Intercept, Dodge and Protective Qi. It is different from preventable external damage returned by Damage Link.', '资源代价或明确注明的直接生命损失，绕过护甲、拦截、闪避与罡气；不同于伤害链接返还的可防外部伤害。', 'Giá tài nguyên hoặc mất sinh lực được ghi rõ là trực tiếp. Bỏ qua Giáp, Chặn Đòn, Né Tránh và Cương Khí Hộ Thể. Khác sát thương bên ngoài có thể phòng do Liên Kết Sát Thương trả lại.'), ['blood']),
  keyword('command', t('Command', '号令', 'Hiệu Lệnh'), t('Orders living summons to attack the chosen enemy. Each summon uses its own attack and statuses; the player’s Strength is not copied to it.', '命令存活召唤物攻击选定敌人；各自使用自身攻击和状态，不复制玩家的力量。', 'Ra lệnh vật triệu hồi còn sống đánh địch được chọn. Mỗi con dùng công kích và trạng thái riêng, không sao chép Sức Mạnh của người chơi.'), ['summoning']),
  keyword('sacrifice', t('Sacrifice', '献祭', 'Hiến Tế'), t('Consumes the stated number of living summons only when enough are present, then summons the named replacement if listed. Sacrifice removes companions; it is not an incoming hit.', '只有存活召唤物数量足够时才消耗注明数量；若列有替代灵兽，随后将其召唤。献祭移除灵伴，不是来袭伤害。', 'Chỉ tiêu số vật triệu hồi còn sống đã ghi khi đủ số lượng, rồi triệu hồi linh thay thế nếu có tên. Hiến Tế loại linh bạn, không phải đòn sát thương đánh tới.'), ['summoning']),
  keyword('mountainBreak', t('Mountain Breaker', '崩山', 'Băng Sơn'), t('Consumes all current Armor and converts it to the listed damage. You lose that Armor even if the attack is defended, so read enemy intent before committing.', '消耗当前全部护甲，按牌面转化为伤害。即使攻击被防住，护甲也已消耗，使用前请读清敌方意图。', 'Tiêu toàn bộ Giáp hiện có và chuyển thành sát thương theo bài. Giáp vẫn mất dù đòn bị phòng, nên đọc ý định địch trước khi quyết định.'), ['earth']),
  keyword('pursuit', t('Pursuit', '追击', 'Truy Kích'), t('Pursuit checks this turn’s play history. Wind Slash requires any earlier Wind card; Chasing Blade must be your third play; Flowing Guard requires the immediately previous card to be an Attack. Bonuses change the original effect, not its hit count.', '追击检查本回合出牌记录：风斩要求此前用过风道牌；追风刃必须是第三张；流风护要求紧前一张是攻击牌。加成作用于原效果，不增加段数。', 'Truy Kích kiểm tra lịch sử dùng bài trong lượt. Phong Trảm cần một lá Phong Đạo đã dùng trước đó; Truy Phong Nhận phải là lá thứ ba; Lưu Phong Hộ cần lá ngay trước là Tấn Công. Phần cộng tăng hiệu ứng gốc, không tăng số đòn.'), ['wind']),
  keyword('calculation', t('Calculation & Deduction', '运筹与推演', 'Tính Toán và Suy Diễn'), t('Wisdom controls future access through drawing, searching, inspecting and ordering the top of the draw pile, and recovering discarded cards. Only explicitly revealed cards become known.', '智道通过抽牌、检索、查看与排列牌库顶、回收弃牌来安排后续资源。只有效果明确揭示的牌才会公开。', 'Trí Đạo sắp tài nguyên tương lai bằng rút, tìm, xem và xếp đầu Chồng Rút, cùng thu hồi bài đã bỏ. Chỉ những lá được hiệu ứng tiết lộ mới trở thành thông tin công khai.'), ['wisdom']),
  keyword('hiddenSchemes', t('Hidden Schemes', '暗谋', 'Ám Kế'), t('Wisdom turns deliberate discard and pile manipulation into draw, Dao Yuan and timing advantages. Trigger text identifies exactly what Active Discard grants.', '智道以有意弃牌与牌堆操控换取抽牌、道元和时机优势；具体收益由主动弃牌触发文字说明。', 'Trí Đạo biến bỏ bài có chủ đích và điều khiển chồng bài thành lợi thế rút bài, Đạo Nguyên và thời cơ. Phần kích hoạt ghi rõ Chủ Động Bỏ Bài đem lại gì.'), ['wisdom']),
  keyword('basic', CATEGORY_NAMES.basic, t('Strike and Defense are the only Basic cards. Basic Mastery can strengthen them; other cards never become Basic merely because they are low grade.', '打击与防御是仅有的基础牌，可被基础精通强化。其他牌不会因品阶低而变成基础牌。', 'Chỉ Đả Kích và Phòng Ngự là bài Cơ Bản. Tinh Thông Cơ Bản có thể tăng chúng; bài khác không trở thành Cơ Bản chỉ vì phẩm thấp.'), ['strength']),
  keyword('divine', CATEGORY_NAMES.divine, t('An ungraded card awarded by a breakthrough. Draw it and pay its cost to activate its persistent combat effect. Owning it in the deck alone gives no passive bonus.', '破境获得的无品阶卡牌。战斗中抽到并支付费用后才激活持续效果，仅拥有此牌不会自动获得加成。', 'Bài không phẩm nhận khi phá cảnh. Phải rút và trả phí để kích năng lực kéo dài trong trận. Chỉ có trong bộ bài chưa đem lại lợi ích thụ động.')),
  keyword('token', CATEGORY_NAMES.token, t(`A generated combat-only card. Flying Sword costs 0, attacks for 2 and Exhausts. Generated cards enter the discard pile if your ${RULES.handSize}-card hand is full.`, `仅存在于战斗中的衍生牌。飞剑耗元0，攻击2，打出后消耗。手牌已满${RULES.handSize}张时，新生成的牌进入弃牌堆。`, `Bài được tạo chỉ trong trận. Phi Kiếm tốn 0, tấn công 2 và Tiêu Hao. Nếu tay đủ ${RULES.handSize} lá, bài tạo mới vào Chồng Bỏ.`), ['sword']),
  keyword('statusCard', CATEGORY_NAMES.status, t('A temporary harmful combat card. It cannot be learned, rewarded, traded, graded or kept in the permanent deck. Read its own play, draw or turn-end rule before handling it.', '临时的有害战斗牌，不可领悟、作为奖励、交易、升品或留在永久牌组。处理前请阅读其打出、抽到或回合结束规则。', 'Bài có hại tạm thời trong chiến đấu. Không thể học, nhận làm thưởng, mua bán, tăng phẩm hay giữ trong bộ bài vĩnh viễn. Đọc quy tắc khi dùng, rút hoặc cuối lượt trước khi xử lý.')),
].map(entry => [entry.id, entry]));

const archetypeDescriptions: Record<string, Text> = {
  explosive: t('Apply Flame, then consume it for a focused burst.', '施加爆炎，再消耗印记集中爆发。', 'Gắn Bạo Viêm rồi tiêu dấu để bộc phát vào một mục tiêu.'),
  spreading: t('Spread marks and damage across the enemy group.', '让印记与伤害蔓延至敌群。', 'Lan dấu và sát thương khắp nhóm địch.'),
  regrowth: t('Restore lost life through immediate and recurring healing.', '以即时与持续回复找回生命。', 'Khôi phục sinh lực đã mất bằng hồi ngay và hồi định kỳ.'),
  seeds: t('Plant delayed damage and healing on enemies.', '在敌方身上种下延迟伤害与回复。', 'Gieo trên địch nguồn sát thương và hồi phục đến sau.'),
  plants: t('Use plant allies for Intercept and automatic attacks.', '以灵植拦截伤害并自动出击。', 'Dùng linh thực Chặn Đòn và tự tấn công.'),
  fortification: t('Build Armor and improve each Armor gain.', '积攒护甲，并提高每次获得的护甲。', 'Tích Giáp và tăng lượng Giáp mỗi lần nhận.'),
  mountain: t('Convert stored Armor into damage at the chosen moment.', '择机将储存的护甲转为伤害。', 'Chọn thời điểm đổi Giáp tích trữ thành sát thương.'),
  flow: t('Gain Yuan, reduce costs and sustain a flexible hand.', '获得道元、降低费用，维持灵活手牌。', 'Nhận Đạo Nguyên, giảm phí và duy trì tay bài linh hoạt.'),
  tide: t('Build Momentum and leave Yuan for the Domain.', '积蓄潮势，为领域留出道元。', 'Tích Triều Thế và để lại Đạo Nguyên cho lĩnh vực.'),
  pierce: t('Prepare extra Attack damage until a hit reaches HP.', '预备攻击增伤，直至一段攻击造成生命损失。', 'Chuẩn bị thêm sát thương Tấn Công cho đến khi một đòn chạm sinh lực.'),
  protective: t('Soften many incoming hits through Protective Qi.', '用护体罡气削弱来袭连击。', 'Dùng Cương Khí Hộ Thể giảm nhiều đòn đánh tới.'),
  intent: t('Accumulate Sword Intent, then choose a multi-hit or consuming payoff.', '凝聚剑意，选择连击或消耗剑意的终结。', 'Tích Kiếm Ý rồi chọn liên kích hoặc đòn tiêu Kiếm Ý.'),
  flying: t('Generate cheap Flying Swords and strengthen every hit.', '生成低费飞剑，强化每次攻击。', 'Tạo Phi Kiếm rẻ và tăng từng đòn đánh.'),
  gale: t('Accumulate Wind Momentum into automatic area damage.', '积蓄风势，自动触发群体伤害。', 'Tích Phong Thế để tự kích sát thương diện rộng.'),
  pursuit: KEYWORD_GLOSSARY.pursuit.description,
  discard: KEYWORD_GLOSSARY.hiddenSchemes.description,
  calculation: KEYWORD_GLOSSARY.calculation.description,
  lifesteal: t('Heal from the HP damage your attack actually deals.', '按攻击实际造成的生命损失回复。', 'Hồi phục theo sinh lực mà đòn đánh thực sự lấy đi.'),
  bleeding: t('Stack Bleeding until its threshold bursts.', '叠加流血，达到阈值后爆发。', 'Cộng Chảy Máu đến ngưỡng để bộc phát.'),
  selfharm: t('Pay direct HP loss for energy, draw or Strength.', '直接付出生命，换取道元、抽牌或力量。', 'Trả sinh lực trực tiếp để đổi Đạo Nguyên, rút bài hoặc Sức Mạnh.'),
  numbers: t('Keep multiple companions to strengthen the team.', '保持多只灵伴，强化全队。', 'Duy trì nhiều linh bạn để tăng sức cả đội.'),
  overwhelm: t('Use at least two companions to weaken the enemy group.', '拥有至少两只灵伴时压制敌群。', 'Có ít nhất hai linh bạn để suy yếu cả nhóm địch.'),
  command: t('Direct companions to attack with their own stats.', '指挥灵伴以各自属性攻击。', 'Ra lệnh linh bạn tấn công bằng chỉ số riêng.'),
  sacrifice: t('Exchange existing companions for a stronger ancestral summon.', '献出已有灵伴，换取强大的祖灵。', 'Đổi linh bạn hiện có lấy vật triệu hồi tổ linh mạnh hơn.'),
  battle: t('Build Strength and apply it to every Attack hit.', '积累力量，强化攻击的每一段。', 'Tích Sức Mạnh để tăng từng đòn Tấn Công.'),
  brute: t('Invest in Basic Mastery so Strike and Defense stay relevant.', '投入基础精通，让打击与防御持续发挥作用。', 'Đầu tư Tinh Thông Cơ Bản để Đả Kích và Phòng Ngự tiếp tục hữu ích.'),
  exhaust: t('Exhaust chosen cards and profit from refining triggers.', '选择消耗卡牌，触发炼化收益。', 'Chọn bài Tiêu Hao và hưởng lợi từ kích hoạt Luyện Hóa.'),
  rerefine: KEYWORD_GLOSSARY.refine.description,
  recover: t('Return eligible cards from the specified pile to hand.', '从指定牌堆将符合条件的牌取回手中。', 'Lấy bài đủ điều kiện từ chồng chỉ định về tay.'),
  setup: t('Hold a prepared Formation through real turn boundaries.', '跨过实际回合保留已布下的阵势。', 'Giữ thế Trận đã chuẩn bị qua các ranh giới lượt thật sự.'),
};
const plans: Record<Path, { keywords: string[]; examples: string[]; pattern: Text; bridge: Text }> = {
  fire: { keywords:['flame'], examples:['ember-brand','cinder-fuse','wildfire-thread'], pattern:t('Mark first; decide between one decisive detonation and spreading across multiple enemies.', '先施印，再决定集中引爆还是向多名敌人蔓延。', 'Gắn dấu trước, rồi chọn kích nổ dứt điểm một địch hay lan sang nhiều địch.'), bridge:t('Wisdom finds detonators; Summoning buys time while Flame builds.', '智道寻找引爆牌，奴道灵伴为积火争取时间。', 'Trí Đạo tìm bài kích nổ; linh bạn Nô Đạo kéo dài thời gian tích lửa.') },
  wood: { keywords:['seed','regen','summon','intercept'], examples:['rootbind','spring-return','thorn-familiar'], pattern:t('Plant Seeds, preserve life, and let growing pressure work across turns.', '种下种子，维持生命，让生长的压力跨回合起效。', 'Gieo Hạt Giống, giữ sinh lực và để sức ép lớn lên qua nhiều lượt.'), bridge:t('Earth Armor protects the healing interval; plants support Summoning numbers.', '土道护甲护住回复间隙，灵植也能补足奴道数量。', 'Giáp Thổ Đạo bảo vệ khoảng hồi phục; linh thực bổ sung số lượng cho Nô Đạo.') },
  earth: { keywords:['armor','fortify','mountainBreak'], examples:['stone-rampart','rooted-stance','mountain-breaker'], pattern:t('Build Armor before Mountain Breaker, while accounting for incoming intent.', '先叠护甲再崩山，同时计算敌方即将执行的意图。', 'Tích Giáp trước Băng Sơn, đồng thời tính ý định địch sắp thực hiện.'), bridge:t('Formation retains a payoff; Metal protection remains after Armor is spent.', '阵道保留终结手段，金道罡气在护甲耗尽后仍能护身。', 'Trận Đạo giữ đòn kết; Cương Khí Kim Đạo vẫn che chở sau khi tiêu Giáp.') },
  water: { keywords:['daoYuan','tidalMomentum','tidalDomain'], examples:['hidden-spring','ripple-guard','ebb-cut'], pattern:t('Reach the Domain threshold and budget at least one Yuan for its turn-end action.', '达到领域阈值，并规划至少一点剩余道元供回合末发动。', 'Đạt ngưỡng lĩnh vực và dự trù ít nhất một Đạo Nguyên cho hành động cuối lượt.'), bridge:t('Wisdom turns spare Yuan into better card access; any Path can use the economy.', '智道把宽裕道元转为更好的抽牌选择，诸道都可利用这份费用优势。', 'Trí Đạo đổi Đạo Nguyên dư thành khả năng lấy bài tốt hơn; mọi Đạo đều dùng được lợi thế phí.') },
  metal: { keywords:['pierce','protectiveQi'], examples:['hone-the-edge','threefold-needles','golden-breath'], pattern:t('Watch which hit will first reach HP; Pierce is consumed then, not merely by Armor damage.', '观察哪一段先伤到生命；破甲此时才消耗，单纯损伤护甲不会消耗。', 'Xem đòn nào sẽ chạm sinh lực đầu tiên; khi đó Xuyên Giáp mới bị tiêu, chỉ gây mất Giáp chưa đủ.'), bridge:t('Strength improves each small hit; Earth and Summoning add other layers of protection.', '力道强化每段小伤害，土道与奴道增加其他防护层。', 'Lực Đạo tăng từng đòn nhỏ; Thổ Đạo và Nô Đạo thêm lớp bảo vệ khác.') },
  sword: { keywords:['swordIntent','token','exhaust'], examples:['still-sword-heart','flying-arsenal','last-word'], pattern:t('Prepare Sword Intent before generating and playing Flying Swords; leave hand space.', '先凝聚剑意，再生成并使用飞剑，注意预留手牌空间。', 'Chuẩn bị Kiếm Ý trước khi tạo và dùng Phi Kiếm; chừa chỗ trên tay.'), bridge:t('Refinement recovers exhausted swords; Formation can prepare more swords over time.', '炼道回收消耗飞剑，阵道可随等待准备更多飞剑。', 'Luyện Đạo thu hồi Phi Kiếm đã Tiêu Hao; Trận Đạo chuẩn bị thêm kiếm theo thời gian.') },
  wind: { keywords:['windMomentum','gale','pursuit','nextWindDiscount'], examples:['wind-slash','wind-step','chasing-blade'], pattern:t('Plan around any earlier Wind play, the exact third play, or an immediately preceding Attack while building Gale.', '围绕此前的风道牌、恰好第三张牌或紧前一张攻击牌安排顺序，同时积蓄狂风。', 'Sắp thứ tự quanh lá Phong Đạo đã dùng, đúng lá thứ ba hoặc lá Tấn Công ngay trước, đồng thời tích Cuồng Phong.'), bridge:t('Wisdom finds the needed card; Water funds it. Other Paths can supply the Attack that enables Flowing Guard.', '智道找齐所需卡牌，水道供给道元，其他道途的攻击也能启动流风护。', 'Trí Đạo tìm lá cần dùng; Thủy Đạo cấp Đạo Nguyên. Tấn Công từ Đạo khác cũng mở điều kiện Lưu Phong Hộ.') },
  blood: { keywords:['bleeding','lifesteal','directLoss'], examples:['crimson-fang','bloodletter','open-vein'], pattern:t('Separate voluntary HP payment from preventable enemy damage, then recover through lifesteal.', '区分主动支付生命与可防的敌方伤害，再以汲血回复。', 'Phân biệt trả sinh lực tự nguyện với sát thương địch có thể phòng, rồi hồi bằng hút sinh lực.'), bridge:t('Wood restores the price paid; Wisdom spends the gained draw and Yuan efficiently.', '木道回复所付代价，智道让换来的抽牌与道元更有效。', 'Mộc Đạo bù giá đã trả; Trí Đạo dùng hiệu quả bài rút và Đạo Nguyên nhận được.') },
  summoning: { keywords:['summon','intercept','command','sacrifice'], examples:['reed-wolf-pact','shared-standard','ancestral-offering'], pattern:t('Choose between keeping a full team, issuing commands and sacrificing it for one powerful ally.', '在保持满员、下令群攻与献祭换取强灵之间取舍。', 'Chọn giữ đội đầy, ra hiệu lệnh hoặc hiến tế để đổi một linh bạn mạnh.'), bridge:t('Wood plants count as companions; Earth Armor protects you from damage remaining after Intercept.', '木道灵植计入灵伴数量，土道护甲保护你承受拦截后的剩余伤害。', 'Linh thực Mộc Đạo tính là đồng đội; Giáp Thổ Đạo bảo vệ bạn trước sát thương còn lại sau Chặn Đòn.') },
  strength: { keywords:['strength','basicPower','basicCost','basic'], examples:['battle-roar','fundamentals','heavy-foundations'], pattern:t('Choose generic Strength for many Attack hits or Basic Mastery for Strike and Defense.', '以力量强化多段攻击，或用基础精通专修打击与防御。', 'Chọn Sức Mạnh cho nhiều đòn Tấn Công, hoặc Tinh Thông Cơ Bản chuyên tăng Đả Kích và Phòng Ngự.'), bridge:t('Metal and Sword offer many hits; Water helps pay increased Basic-card costs.', '金道与剑道提供多段攻击，水道帮助支付提高的基础牌费用。', 'Kim Đạo và Kiếm Đạo có nhiều đòn; Thủy Đạo giúp trả phí bài Cơ Bản tăng thêm.') },
  refinement: { keywords:['exhaust','refine'], examples:['burn-impurities','crucible-shell','re-refinement'], pattern:t('Thin this combat’s cycle through Exhaust, profit from triggers, then recover or re-refine key cards.', '消耗牌以精简本场循环，收获触发收益，再回收或重炼关键牌。', 'Dùng Tiêu Hao tinh gọn vòng bài trong trận, hưởng kích hoạt rồi thu hồi hoặc Trọng Luyện lá then chốt.'), bridge:t('Flying Swords feed the furnace; Wisdom locates cards worth recovering.', '飞剑为炉火提供材料，智道寻找值得回收的牌。', 'Phi Kiếm nuôi lò; Trí Đạo tìm lá đáng thu hồi.') },
  formation: { keywords:['retain','armor'], examples:['hidden-thunder-array','mountain-seal','silent-array'], pattern:t('Retain a chosen plan while using other cards to survive; release when its actual retained bonus matters.', '保留选定阵势，同时用其他牌求生，在实际保留加成足够时释放。', 'Giữ thế trận đã chọn và dùng bài khác để sống; phát động khi phần tăng từ số lượt giữ thực sự có ích.'), bridge:t('Earth and Metal defend the waiting turns; Wisdom refreshes the rest of the hand.', '土道与金道保护等待回合，智道更新其他手牌。', 'Thổ Đạo và Kim Đạo bảo vệ những lượt chờ; Trí Đạo làm mới phần tay bài còn lại.') },
  wisdom: { keywords:['calculation','hiddenSchemes','activeDiscard'], examples:['read-the-current','exchange-thought','ragged-banner'], pattern:t('Plan future draws with Calculation & Deduction, or deliberately discard Hidden Schemes for immediate resources.', '用运筹与推演安排未来抽牌，或主动弃置暗谋牌换取即时资源。', 'Dùng Tính Toán và Suy Diễn sắp lượt rút sau, hoặc chủ động bỏ Ám Kế để lấy tài nguyên ngay.'), bridge:t('Every Path benefits from finding its enablers and payoffs. Forced enemy discard can trigger a retained scheme.', '诸道都受益于找到启动与终结牌；敌方强迫弃牌也可触发保留的暗谋。', 'Mọi Đạo đều hưởng lợi khi tìm được lá mở và lá kết. Bị địch ép bỏ cũng có thể kích Ám Kế đã giữ.') },
};
export const DAO_ENCYCLOPEDIA: DaoEntry[] = PATHS.map(path => {
  const plan = plans[path.id];
  const arts = Object.values(CARDS).filter(card => card.path === path.id && (card.category === 'dao' || card.category === 'immortal'));
  const archetypes = [...new Set(arts.map(card => card.archetype))].map(id => {
    if (!archetypeDescriptions[id]) throw new Error(`Missing authored archetype help: ${id}`);
    return { id, name: ARCHETYPES[id], description: archetypeDescriptions[id], cardIds: arts.filter(card => card.archetype === id).map(card => card.id) };
  });
  return { id: path.id, name: path.name, description: path.description, archetypes, keywords: plan.keywords, exampleCardIds: plan.examples, playPattern: plan.pattern, crossPath: plan.bridge };
});
/** Alias retained for simple consumers that call this data a glossary. */
export const TRANSLATION_GLOSSARY = KEYWORD_GLOSSARY;
