// Copyright 2026 Ye Zhou
// SPDX-License-Identifier: Apache-2.0

import type { Locale, Status, Text } from './types';
export const SUPPORTED_LOCALES = ['en', 'zh-CN', 'vi'] as const;
export const copy = {
 continue:{en:'Continue journey','zh-CN':'继续道途',vi:"Tiếp tục đạo trình"},newRun:{en:'Begin a new life','zh-CN':'开启此生',vi:"Bắt đầu một kiếp mới"},collection:{en:'Book of techniques','zh-CN':'万法图鉴',vi:"Vạn Pháp Đồ Giám"},history:{en:'Lives remembered','zh-CN':'前尘录',vi:"Tiền Trần Lục"},settings:{en:'Settings','zh-CN':'设置',vi:"Cài đặt"},back:{en:'Return','zh-CN':'返回',vi:"Trở lại"},close:{en:'Close','zh-CN':'关闭',vi:"Đóng"},
 human:{en:'HUMAN REALM','zh-CN':'人界',vi:"NHÂN GIỚI"},life:{en:'A life written in cards','zh-CN':'以牌入道，一生问天',vi:"Lấy bài nhập đạo, một đời hỏi trời"},menu:{en:'Menu','zh-CN':'菜单',vi:"Trình đơn"},deck:{en:'Deck','zh-CN':'牌组',vi:"Bộ bài"},stones:{en:'Spirit stones','zh-CN':'灵石',vi:"Linh thạch"},hp:{en:'Life','zh-CN':'生命',vi:"Sinh lực"},armor:{en:'Armor','zh-CN':'护甲',vi:"Giáp"},energy:{en:'Dao Yuan','zh-CN':'道元',vi:"Đạo Nguyên"},
 starting:{en:'Choose your first teachings','zh-CN':'择法入道',vi:"Chọn pháp nhập đạo"},startingHint:{en:'Choose one Dao Art. Your paths may cross and change throughout this life.','zh-CN':'选择一张道术。此生可兼修诸道，随时转变方向。',vi:"Chọn một Đạo Thuật. Trong kiếp này, bạn có thể tu nhiều Đạo và đổi hướng bất cứ lúc nào."},choose:{en:'Learn this technique','zh-CN':'领悟此术',vi:"Lĩnh ngộ thuật này"},round:{en:'Teaching {n} of 2','zh-CN':'第{n}次择法 · 共2次',vi:"Lần chọn {n} / 2"},
 road:{en:'The Dao Road','zh-CN':'道途',vi:"Đạo Lộ"},roadHint:{en:'Only the next step is yours to know.','zh-CN':'天机隐于雾中，唯有脚下可知。',vi:"Thiên cơ ẩn trong sương; chỉ bước tiếp theo thuộc về bạn."},omen:{en:'HEAVENLY OMEN','zh-CN':'天象预兆',vi:"ĐIỀM TRỜI"},enter:{en:'Take this road','zh-CN':'踏上此路',vi:"Bước lên đường này"},unknown:{en:'Beyond the mist','zh-CN':'云深不知处',vi:"Phía sau màn sương"},
 turn:{en:'YOUR TURN · {n}','zh-CN':'你的回合 · {n}',vi:"LƯỢT CỦA BẠN · {n}"},endTurn:{en:'End turn','zh-CN':'结束回合',vi:"Kết thúc lượt"},cancel:{en:'Cancel','zh-CN':'取消',vi:"Hủy"},target:{en:'Choose an enemy. Escape to cancel.','zh-CN':'选择敌人。按Esc取消。',vi:"Chọn một kẻ địch. Nhấn Esc để hủy."},play:{en:'Play','zh-CN':'使用',vi:"Sử dụng"},inspect:{en:'Inspect card','zh-CN':'查看卡牌',vi:"Xem bài"},draw:{en:'Draw pile','zh-CN':'抽牌堆',vi:"Chồng Rút"},discard:{en:'Discard','zh-CN':'弃牌堆',vi:"Chồng Bỏ"},exhaust:{en:'Exhaust','zh-CN':'消耗堆',vi:"Chồng Tiêu Hao"},hand:{en:'Hand','zh-CN':'手牌',vi:"Tay bài"},log:{en:'Combat record','zh-CN':'战斗记录',vi:"Nhật ký chiến đấu"},
 victory:{en:'The road is yours again','zh-CN':'此路已通',vi:"Đường đã thông"},rewardHint:{en:'Carry one new technique into the life ahead, or keep your deck focused.','zh-CN':'领悟一门新术，或保持牌组精炼。',vi:"Lĩnh ngộ một thuật mới cho hành trình phía trước, hoặc giữ bộ bài tinh gọn."},skip:{en:'Leave this reward','zh-CN':'放弃奖励',vi:"Bỏ qua phần thưởng"},acquire:{en:'Add to deck','zh-CN':'加入牌组',vi:"Thêm vào bộ bài"},
 breakthrough:{en:'The heavens yield','zh-CN':'破境',vi:"Phá cảnh"},breakthroughHint:{en:'A Divine Ability is offered. Draw and activate it in combat to awaken its power.','zh-CN':'天劫赠予神通。战斗中抽到并消耗道元，方可激活。',vi:"Thiên kiếp ban một Thần Thông. Hãy rút được và tiêu Đạo Nguyên trong chiến đấu để kích hoạt."},foundationHint:{en:'These techniques are optional. Learn a card or leave this reward.','zh-CN':'这些术法可自由选择。领悟一张，或放弃本次奖励。',vi:"Những thuật pháp này là tùy chọn. Lĩnh ngộ một lá hoặc bỏ qua phần thưởng."},
 merchant:{en:'The thousand-mile emporium','zh-CN':'千里坊',vi:"Thiên Lý Phường"},merchantHint:{en:'Every technique has its price. Every empty space has its value.','zh-CN':'万法皆有价，取舍亦是道。',vi:"Mọi thuật pháp đều có giá. Mỗi chỗ trống cũng có giá trị."},stock:{en:'Techniques for sale','zh-CN':'在售术法',vi:"Thuật pháp đang bán"},buy:{en:'Buy','zh-CN':'购买',vi:"Mua"},sell:{en:'Sell','zh-CN':'出售',vi:"Bán"},upgrade:{en:'Upgrade','zh-CN':'升品',vi:"Tăng phẩm"},leave:{en:'Continue onward','zh-CN':'继续前行',vi:"Tiếp tục lên đường"},sold:{en:'Acquired','zh-CN':'已购入',vi:"Đã mua"},saleHint:{en:'Up to 3 sales · keep at least {n} cards','zh-CN':'最多出售3张 · 至少保留{n}张',vi:"Tối đa 3 lần bán · giữ ít nhất {n} lá"},upgradeHint:{en:'Two refinements · the second costs more','zh-CN':'可付费升品两次 · 第二次费用更高',vi:"Hai lần tăng phẩm có phí · lần thứ hai đắt hơn"},
 rest:{en:'A moment beneath the pines','zh-CN':'松下片刻',vi:"Khoảnh khắc dưới tán tùng"},restHint:{en:'Mend the body, or sharpen the spirit. Choose one.','zh-CN':'疗养身躯，或精进术法。二者择一。',vi:"Dưỡng thân hoặc tinh luyện thuật pháp. Chọn một."},heal:{en:'Rest & recover','zh-CN':'静息疗伤',vi:"Nghỉ ngơi hồi phục"},freeUpgrade:{en:'Refine one technique','zh-CN':'精进一术',vi:"Tinh luyện một thuật"},healHint:{en:'Recover {n} HP (25% of maximum life).','zh-CN':'回复{n}点生命（上限的25%）。',vi:"Hồi {n} sinh lực (25% sinh lực tối đa)."},
 inheritance:{en:'What the ancients left behind','zh-CN':'古人遗泽',vi:"Di Trạch Tiền Nhân"},inheritanceHint:{en:'Their life is over. Their understanding need not be.','zh-CN':'前人已逝，道法犹存。',vi:"Đời người đã hết, nhưng hiểu biết vẫn có thể truyền lại."},
 dead:{en:'This life returns to silence','zh-CN':'此生归寂',vi:"Kiếp này về tĩnh lặng"},deadHint:{en:'The road remembers your choices. Another life begins with new possibilities.','zh-CN':'道途铭记你的选择，来生仍有万千可能。',vi:"Đạo lộ nhớ những lựa chọn của bạn. Kiếp sau vẫn còn muôn khả năng."},ascended:{en:'Beyond the mortal heavens','zh-CN':'一朝飞升',vi:"Vượt khỏi trời phàm"},ascendedHint:{en:'You have completed the Human Realm. This life is written among the stars.','zh-CN':'你已渡尽人界诸劫，此生留名星河。',vi:"Bạn đã hoàn thành Nhân Giới. Kiếp này được ghi giữa tinh hà."},returnMenu:{en:'Return to the beginning','zh-CN':'重返山门',vi:"Trở về sơn môn"},newLife:{en:'Begin another life','zh-CN':'再启一生',vi:"Mở một kiếp khác"},highestRealm:{en:'Highest realm','zh-CN':'最高境界',vi:"Cảnh giới cao nhất"},combats:{en:'Encounters won','zh-CN':'遭遇胜场',vi:"Số trận thắng"},elites:{en:'Elites defeated','zh-CN':'击败精英',vi:"Tinh Anh đã hạ"},tribulations:{en:'Tribulations cleared','zh-CN':'渡劫次数',vi:"Thiên kiếp đã vượt"},cards:{en:'Techniques learned','zh-CN':'领悟术法',vi:"Thuật pháp đã học"},
 allPaths:{en:'All paths','zh-CN':'全部道途',vi:"Mọi Đạo"},search:{en:'Search name or keyword','zh-CN':'搜索名称或关键词',vi:"Tìm tên hoặc từ khóa"},discovered:{en:'Discovered','zh-CN':'已发现',vi:"Đã khám phá"},undiscovered:{en:'Yet to be discovered','zh-CN':'尚待发现',vi:"Chưa khám phá"},noHistory:{en:'No life has ended yet. Your story is waiting.','zh-CN':'尚无前尘可记，你的故事正待展开。',vi:"Chưa kiếp nào kết thúc. Câu chuyện của bạn đang chờ."},
 sound:{en:'Sound','zh-CN':'声音',vi:"Âm thanh"},music:{en:'Ambient music','zh-CN':'环境音乐',vi:"Nhạc nền"},sfx:{en:'Sound effects','zh-CN':'音效',vi:"Hiệu ứng âm thanh"},motion:{en:'Motion','zh-CN':'动态效果',vi:"Chuyển động"},speed:{en:'Animation speed','zh-CN':'动画速度',vi:"Tốc độ hoạt ảnh"},reduce:{en:'Reduce motion','zh-CN':'减少动态效果',vi:"Giảm chuyển động"},onboarding:{en:'Show guidance','zh-CN':'显示引导',vi:"Hiện hướng dẫn"},locale:{en:'Language','zh-CN':'语言',vi:"Ngôn ngữ"},save:{en:'Saved on this device','zh-CN':'已保存至本机',vi:"Đã lưu trên thiết bị này"},saveError:{en:'Unable to save. Your last committed action is protected. Export a recovery file before continuing.','zh-CN':'无法保存。上次完成的行动仍受保护，请先导出恢复文件。',vi:"Không thể lưu. Hành động đã lưu gần nhất vẫn được bảo vệ. Hãy xuất tệp phục hồi trước khi tiếp tục."},saveConflict:{en:'Another tab has advanced this journey. Loading its latest state.','zh-CN':'另一标签页已推进道途，正在载入最新状态。',vi:"Một thẻ khác đã tiến xa hơn trong đạo trình này. Đang tải trạng thái mới nhất."},corrupt:{en:'This save could not be verified. The original has been preserved for recovery.','zh-CN':'存档未能通过校验。原始数据已保留，供后续恢复。',vi:"Không thể xác minh bản lưu này. Dữ liệu gốc đã được giữ lại để phục hồi."},export:{en:'Export diagnostic file','zh-CN':'导出诊断文件',vi:"Xuất tệp chẩn đoán"},retry:{en:'Reload saved journey','zh-CN':'重新载入存档',vi:"Tải lại đạo trình đã lưu"},
 confirmSell:{en:'Sell this technique?','zh-CN':'出售这门术法？',vi:"Bán thuật pháp này?"},confirmSellHint:{en:'It leaves your permanent deck for this life.','zh-CN':'此牌将离开本次道途的永久牌组。',vi:"Lá này sẽ rời bộ bài vĩnh viễn trong kiếp hiện tại."},confirmRetire:{en:'Bring this life to an end?','zh-CN':'结束此生？',vi:"Kết thúc kiếp này?"},confirmRetireHint:{en:'This journey will be recorded as a death. It cannot be resumed.','zh-CN':'本次道途将以死亡记录，无法继续。',vi:"Đạo trình sẽ được ghi là tử vong và không thể tiếp tục."},retire:{en:'Relinquish this life','zh-CN':'结束此生',vi:"Buông bỏ kiếp này"},
 compare:{en:'Refinement preview','zh-CN':'升品对照',vi:"Xem trước tăng phẩm"},current:{en:'Current','zh-CN':'当前',vi:"Hiện tại"},after:{en:'After refinement','zh-CN':'升品后',vi:"Sau tăng phẩm"},
 hiddenOrder:{en:'Draw order is hidden. Cards are listed alphabetically.','zh-CN':'抽牌顺序未公开，此处按名称排列。',vi:"Thứ tự rút được giữ kín. Danh sách này xếp theo tên."},choice:{en:'Shape the next moment','zh-CN':'定下一步',vi:"Định bước tiếp theo"},confirmChoice:{en:'Confirm selection','zh-CN':'确认选择',vi:"Xác nhận lựa chọn"},tidal:{en:'Tidal Domain','zh-CN':'潮汐领域',vi:"Lĩnh Vực Thủy Triều"},tidalHint:{en:'Choose a state. It acts at turn end if at least 1 Dao Yuan remains.','zh-CN':'选择状态。回合结束时剩余至少1道元，领域才会发动。',vi:"Chọn một trạng thái. Lĩnh vực phát động cuối lượt nếu còn ít nhất 1 Đạo Nguyên."},
 rising:{en:'Rising Tide','zh-CN':'涨潮',vi:"Triều Dâng"},tranquil:{en:'Tranquil Sea','zh-CN':'静海',vi:"Biển Lặng"},raging:{en:'Raging Tide','zh-CN':'怒涛',vi:"Sóng Dữ"},risingHint:{en:'Strike the lowest-HP enemy for 3 + Momentum. Gain 1 Momentum.','zh-CN':'对生命最低的敌人造成3+潮势伤害，然后获得1潮势。',vi:"Gây 3 + Triều Thế sát thương cho địch ít sinh lực nhất. Nhận 1 Triều Thế."},tranquilHint:{en:'Gain 3 + 2 × Momentum Armor. Lose 1 Momentum.','zh-CN':'获得3+2×潮势护甲，然后失去1潮势。',vi:"Nhận 3 + 2 × Triều Thế Giáp. Mất 1 Triều Thế."},ragingHint:{en:'Strike the highest-HP enemy for 4 + 2 × Momentum. Lose 1 Momentum.','zh-CN':'对生命最高的敌人造成4+2×潮势伤害，然后失去1潮势。',vi:"Gây 4 + 2 × Triều Thế sát thương cho địch nhiều sinh lực nhất. Mất 1 Triều Thế."},
 tutorial1:{en:'Read their intent. Play a card, then choose a target. Unused Armor halves at your next turn start.','zh-CN':'先看敌方意图。点击卡牌，再选择目标。未用完的护甲在你的下回合开始时减半。',vi:"Đọc ý định của địch. Chọn bài rồi chọn mục tiêu. Giáp chưa dùng hết giảm một nửa ở đầu lượt tiếp theo."},tutorial2:{en:'Each turn refills Dao Yuan and draws five cards. Unplayed cards are discarded unless they Retain.','zh-CN':'每回合恢复道元并抽五张牌。未用的牌进入弃牌堆，保留牌除外。',vi:"Mỗi lượt hồi đầy Đạo Nguyên và rút năm lá. Bài chưa dùng vào Chồng Bỏ, trừ bài có Giữ Lại."},shortcuts:{en:'1–0 select · Tab focus target · Enter confirm · E end turn · Esc cancel','zh-CN':'1–0选牌 · Tab聚焦目标 · Enter确认 · E结束回合 · Esc取消',vi:"1–0 chọn bài · Tab chọn mục tiêu · Enter xác nhận · E kết thúc lượt · Esc hủy"},
 noCloud:{en:'Local saves · No account required','zh-CN':'本机存档 · 无需账号',vi:"Lưu trên thiết bị · Không cần tài khoản"},summons:{en:'Spirit companions','zh-CN':'灵伴',vi:"Linh bạn"},noSummons:{en:'No companions summoned','zh-CN':'尚未召唤灵伴',vi:"Chưa triệu hồi linh bạn"},permanent:{en:'Permanent deck','zh-CN':'永久牌组',vi:"Bộ bài vĩnh viễn"},retained:{en:'Retained {n} turns','zh-CN':'已保留{n}回合',vi:"Đã giữ {n} lượt"},temporary:{en:'Temporary refinement','zh-CN':'临时升品',vi:"Tăng phẩm tạm thời"},ungraded:{en:'Ungraded','zh-CN':'无品阶',vi:"Không có phẩm"},seed:{en:'Seed','zh-CN':'种子',vi:"Hạt giống"},empty:{en:'No matching techniques','zh-CN':'没有符合条件的术法',vi:"Không có thuật pháp phù hợp"},previewUnknown:{en:'Further effects require a choice or hidden information.','zh-CN':'后续效果涉及选择或未公开信息。',vi:"Hiệu ứng tiếp theo cần lựa chọn hoặc thông tin chưa được tiết lộ."},
 cosmetic:{en:'Card back','zh-CN':'牌背',vi:"Mặt sau bài"},defaultBack:{en:'Heavenly seal','zh-CN':'天印',vi:"Thiên Ấn"},inkBack:{en:'Ink memory','zh-CN':'墨忆',vi:"Mặc Ức"},ascendantBack:{en:'Ascendant gold','zh-CN':'飞升金',vi:"Phi Thăng Kim"},unlockHint:{en:'Discover new card backs and lore through completed lives. Combat stats never carry over.','zh-CN':'完成道途可解锁牌背与故事，战斗属性不会继承。',vi:"Hoàn thành các kiếp để mở mặt sau bài và truyện. Chỉ số chiến đấu không được kế thừa."}
} satisfies Record<string,Text>;
export type CopyKey=keyof typeof copy;
export function tr(locale:Locale,key:CopyKey,vars:Record<string,string|number>={}){return copy[key][locale].replace(/\{(\w+)\}/g,(_,k)=>String(vars[k]??`{${k}}`));}
export { GRADE_NAMES } from './content';
const text = (en: string, zh: string, vi: string): Text => ({ en, 'zh-CN': zh, vi });
export const CATEGORY_NAMES = {
  basic: text('Basic', '基础', 'Cơ Bản'),
  dao: text('Dao Art', '道术', 'Đạo Thuật'),
  immortal: text('Immortal Art', '仙术', 'Tiên Thuật'),
  divine: text('Divine Ability', '神通', 'Thần Thông'),
  token: text('Token', '衍生', 'Phái Sinh'),
  status: text('Status Card', '状态牌', 'Bài Trạng Thái'),
};
export const STATUS_NAMES: Record<Status, Text> = {
  strength: text('Strength', '力量', 'Sức Mạnh'),
  fortify: text('Fortify', '坚固', 'Kiên Cố'),
  weak: text('Weak', '虚弱', 'Suy Yếu'),
  vulnerable: text('Vulnerable', '易伤', 'Dễ Tổn Thương'),
  poison: text('Poison', '中毒', 'Trúng Độc'),
  pierce: text('Armor Pierce', '破甲', 'Xuyên Giáp'),
  protectiveQi: text('Protective Qi', '罡气护体', 'Cương Khí Hộ Thể'),
  swordIntent: text('Sword Intent', '剑意', 'Kiếm Ý'),
  tidalMomentum: text('Tidal Momentum', '潮势', 'Triều Thế'),
  windMomentum: text('Wind Momentum', '风势', 'Phong Thế'),
  bleeding: text('Bleeding', '流血', 'Chảy Máu'),
  flame: text('Explosive Flame', '爆炎', 'Bạo Viêm'),
  seed: text('Seeds', '种子', 'Hạt Giống'),
  regen: text('Regeneration', '再生', 'Tái Sinh'),
  dodge: text('Dodge', '闪避', 'Né Tránh'),
  reduction: text('Damage Reduction', '减伤', 'Giảm Sát Thương'),
  basicPower: text('Basic Mastery', '基础精通', 'Tinh Thông Cơ Bản'),
  basicCost: text('Basic Dao Yuan Surcharge', '基础耗元增加', 'Phụ Phí Đạo Nguyên Cơ Bản'),
  link: text('Damage Link', '伤害链接', 'Liên Kết Sát Thương'),
  restriction: text('Restriction', '禁制', 'Cấm Chế'),
  energyDebt: text('Dao Yuan Debt', '道元负债', 'Nợ Đạo Nguyên'),
};
