import type { Locale, Text } from './types';
export const uiCopy = {
 encyclopedia:{en:'Dao Encyclopedia','zh-CN':'道法百科',vi:'Bách khoa Đạo pháp'},
 beginner:{en:'First steps','zh-CN':'初入道途',vi:'Bước đầu tu luyện'},
 keywords:{en:'Keywords & interactions','zh-CN':'关键词与机制',vi:'Từ khóa và tương tác'},
 gradeDisplay:{en:'Card grade display','zh-CN':'卡牌品阶显示',vi:'Cách hiển thị phẩm bài'},
 numeric:{en:'Numbers · 1–8','zh-CN':'数字 · 1–8级',vi:'Số · cấp 1–8'},
 letters:{en:'Letters · F → SS','zh-CN':'字母 · F → SS',vi:'Chữ · F → SS'},
 traditional:{en:'Traditional · Ding → Tian','zh-CN':'传统 · 丁 → 天',vi:'Truyền thống · Đinh → Thiên'},
 gradeOrder:{en:'Higher means stronger. Display style does not change the rules.','zh-CN':'越往后品阶越高。显示方式不改变规则。',vi:'Càng về sau, phẩm càng cao. Cách hiển thị không thay đổi luật chơi.'},
 grade:{en:'Grade {n}','zh-CN':'{n}级',vi:'Cấp {n}'},
 attack:{en:'Attack','zh-CN':'攻击',vi:'Tấn công'},
 defense:{en:'Defense','zh-CN':'防御',vi:'Phòng thủ'},
 skill:{en:'Skill','zh-CN':'技能',vi:'Kỹ năng'},
 power:{en:'Persistent power','zh-CN':'持续能力',vi:'Sức mạnh duy trì'},
 rulesType:{en:'Rules type: {type}','zh-CN':'规则类型：{type}',vi:'Loại theo luật: {type}'},
 temporaryStatus:{en:'Combat only · Negative','zh-CN':'仅限本战 · 负面牌',vi:'Chỉ trong trận · Bài bất lợi'},
 copies:{en:'Copy {n}','zh-CN':'第{n}张',vi:'Bản {n}'},
 unmet:{en:'Condition not met','zh-CN':'条件未满足',vi:'Chưa đủ điều kiện'},
 met:{en:'Condition met','zh-CN':'条件已满足',vi:'Đã đủ điều kiện'},
 player:{en:'The Wanderer','zh-CN':'行道者',vi:'Người Lữ Hành'},
 selfTarget:{en:'Select your portrait, or double-click this card.','zh-CN':'选择自己的头像，或双击此牌。',vi:'Chọn chân dung của bạn hoặc nhấp đúp lá bài này.'},
 enemyTarget:{en:'Choose a living enemy. Double-click selects this card; it does not attack.','zh-CN':'选择存活的敌人。双击只进入目标选择，不会自动攻击。',vi:'Chọn một kẻ địch còn sống. Nhấp đúp chỉ chọn bài, chưa tấn công.'},
 allEnemiesTarget:{en:'Affects all enemies. Drop on any living enemy, or confirm here.','zh-CN':'作用于所有敌人。拖到任一存活敌人，或在此确认。',vi:'Tác động lên mọi kẻ địch. Thả vào một kẻ địch còn sống hoặc xác nhận tại đây.'},
 randomEnemyTarget:{en:'The game chooses a random enemy when played. Drop on a living enemy, or confirm here.','zh-CN':'施放时随机选取敌人。拖到任一存活敌人，或在此确认。',vi:'Chọn kẻ địch ngẫu nhiên khi dùng. Thả vào một kẻ địch còn sống hoặc xác nhận tại đây.'},
 noTarget:{en:'No unit target. Double-click this card, or confirm here.','zh-CN':'无需单位目标。双击此牌，或在此确认。',vi:'Không cần mục tiêu. Nhấp đúp lá bài hoặc xác nhận tại đây.'},
 playSelected:{en:'Play selected card','zh-CN':'施放所选卡牌',vi:'Dùng lá bài đã chọn'},
 deckMinimum:{en:'Permanent cards: {current}. This realm requires at least {minimum} after removal.','zh-CN':'当前永久牌组{current}张；移除后不得低于本境界的{minimum}张。',vi:'Bộ bài vĩnh viễn: {current} lá. Sau khi loại bài, cảnh giới này yêu cầu ít nhất {minimum} lá.'},
 noDeckMaximum:{en:'No maximum deck size. Rewards can always be skipped.','zh-CN':'牌组没有张数上限，所有卡牌奖励均可跳过。',vi:'Không giới hạn số lá tối đa. Luôn có thể bỏ qua phần thưởng bài.'},
 stageAdvanced:{en:'Cultivation advanced','zh-CN':'修为精进',vi:'Tu vi tiến triển'},
 received:{en:'Already received','zh-CN':'已经到账',vi:'Đã nhận'},
 stillToChoose:{en:'Optional choice — not yet claimed','zh-CN':'可选奖励——尚未领取',vi:'Lựa chọn tùy chọn — chưa nhận'},
 optionalReward:{en:'{options} options · take up to {count}, or Skip','zh-CN':'{options}张备选 · 最多领取{count}张，也可跳过',vi:'{options} lựa chọn · nhận tối đa {count} lá hoặc bỏ qua'},
 maxHealth:{en:'Maximum HP','zh-CN':'生命上限',vi:'HP tối đa'},
 maxEnergy:{en:'Maximum Dao Yuan','zh-CN':'道元上限',vi:'Đạo Nguyên tối đa'},
 normalGradeLabel:{en:'Normal card grade','zh-CN':'常规卡牌品阶',vi:'Phẩm bài thông thường'},
 receivedHealing:{en:'Healed {n} HP','zh-CN':'实际回复{n}生命',vi:'Đã hồi {n} HP'},
 receivedStones:{en:'+{n} spirit stones','zh-CN':'获得{n}灵石',vi:'+{n} linh thạch'},
 acquiredChoice:{en:'Reward claimed','zh-CN':'奖励已领取',vi:'Đã nhận phần thưởng'},
 wrongSelf:{en:'This card targets you. Drop it on your portrait.','zh-CN':'这张牌作用于自身，请拖到自己的头像。',vi:'Lá bài này tác động lên bạn. Hãy thả vào chân dung của bạn.'},
 wrongEnemy:{en:'This card needs an enemy target.','zh-CN':'这张牌需要敌方目标。',vi:'Lá bài này cần mục tiêu là kẻ địch.'},
 unresolved:{en:'Resolve the current choice first.','zh-CN':'请先完成当前选择。',vi:'Hãy hoàn tất lựa chọn hiện tại trước.'},
 damageHits:{en:'Individual hits','zh-CN':'逐段伤害',vi:'Sát thương từng đòn'},
 self:{en:'Self','zh-CN':'自身',vi:'Bản thân'},
 commandTotal:{en:'Command: {n}','zh-CN':'号令：{n}',vi:'Hiệu Lệnh: {n}'},
 warningHit:{en:'Next turn: {n}','zh-CN':'下回合：{n}',vi:'Lượt sau: {n}'},
 beastThreat:{en:'+{n} beasts · total {total}','zh-CN':'兽群+{n} · 合计{total}',vi:'Thú +{n} · tổng {total}'},
 rawAttack:{en:'{hits} hit(s), {amount} damage each. Total raw damage: {total}.','zh-CN':'攻击{hits}次，每次{amount}点伤害，原始总伤害{total}。',vi:'{hits} đòn, mỗi đòn gây {amount} sát thương. Tổng sát thương gốc: {total}.'},
 currentLocation:{en:'You are here','zh-CN':'当前所在',vi:'Bạn đang ở đây'},
 history:{en:'Steps already taken','zh-CN':'已行之路',vi:'Những bước đã qua'},
 pathChoice:{en:'Choose one immediate branch','zh-CN':'选择眼前的一条分支',vi:'Chọn một nhánh ngay phía trước'},
 seller:{en:'Keeper of the Thousand-Mile Pavilion','zh-CN':'千里阁掌柜',vi:'Chủ Các Ngàn Dặm'},
 sellerLine:{en:'“A technique is worth what it makes possible.”','zh-CN':'“术法之价，在于所能成就之事。”',vi:'“Giá trị của thuật pháp nằm ở điều nó giúp bạn làm được.”'},
 notEnough:{en:'Need {n} more spirit stones.','zh-CN':'还需{n}灵石。',vi:'Cần thêm {n} linh thạch.'},
 purchased:{en:'Purchased this visit','zh-CN':'本次已购入',vi:'Đã mua trong lần ghé này'},
 chooseUpgrade:{en:'Choose a card to refine','zh-CN':'选择升品卡牌',vi:'Chọn lá bài để nâng cấp'},
 chooseSale:{en:'Choose a card to sell','zh-CN':'选择出售卡牌',vi:'Chọn lá bài để bán'},
 another:{en:'Choose another card','zh-CN':'另选一张',vi:'Chọn lá bài khác'},
 confirmUpgrade:{en:'Confirm refinement','zh-CN':'确认升品',vi:'Xác nhận nâng cấp'},
 confirmRest:{en:'Confirm rest','zh-CN':'确认静息',vi:'Xác nhận nghỉ ngơi'},
 noUpgrades:{en:'No eligible cards at this realm.','zh-CN':'当前境界没有可升品的卡牌。',vi:'Không có lá bài đủ điều kiện ở cảnh giới này.'},
 maxGrade:{en:'Maximum usable grade at this realm: {grade}.','zh-CN':'当前境界最高可用品阶：{grade}。',vi:'Phẩm cao nhất có thể dùng ở cảnh giới này: {grade}.'},
 normalGrade:{en:'Normal realm grade: {grade}.','zh-CN':'当前境界常规品阶：{grade}。',vi:'Phẩm thông thường của cảnh giới: {grade}.'},
 allowance:{en:'Remaining uses: {n}','zh-CN':'剩余次数：{n}',vi:'Số lượt còn lại: {n}'},
 saleMinimum:{en:'Selling must leave at least {n} permanent cards.','zh-CN':'出售后必须至少保留{n}张永久卡牌。',vi:'Sau khi bán phải còn ít nhất {n} lá bài vĩnh viễn.'},
 limit:{en:'This visit’s allowance is used up.','zh-CN':'本次可用次数已用完。',vi:'Đã dùng hết số lượt trong lần ghé này.'},
 stale:{en:'The journey changed. Choose the card again to refresh the quote.','zh-CN':'道途状态已变化，请重新选牌获取报价。',vi:'Trạng thái hành trình đã thay đổi. Chọn lại lá bài để cập nhật báo giá.'},
 unchanged:{en:'Cost unchanged','zh-CN':'道元消耗不变',vi:'Chi phí Đạo Nguyên không đổi'},
 previewOnly:{en:'Preview only. Nothing is spent until you confirm.','zh-CN':'当前仅为预览，确认前不会消耗任何资源。',vi:'Chỉ xem trước. Chưa tiêu tốn gì cho đến khi xác nhận.'},
 fullHealth:{en:'Already at full HP · heals 0.','zh-CN':'生命已满 · 实际回复0。',vi:'HP đã đầy · hồi 0 HP.'},
 healActual:{en:'Recover {n} HP, capped at maximum life.','zh-CN':'实际回复{n}生命，不超过生命上限。',vi:'Hồi {n} HP, không vượt quá HP tối đa.'},
 legacyTime:{en:'Previous version · {n} elapsed min','zh-CN':'旧版记录 · 经过{n}分钟',vi:'Phiên bản trước · {n} phút đã trôi qua'},
 activeTime:{en:'Active time · {n} min','zh-CN':'活跃用时 · {n}分钟',vi:'Thời gian hoạt động · {n} phút'},
 reorderHint:{en:'Choose all {n} cards in your preferred draw order. First selected is drawn first. Selected: {selected}.','zh-CN':'按希望的抽取顺序选择全部{n}张牌。先选的先抽，已选{selected}张。',vi:'Chọn đủ {n} lá theo thứ tự muốn rút. Lá chọn đầu sẽ được rút trước. Đã chọn: {selected}.'},
 chooseCount:{en:'Choose up to {n} cards. Selected: {selected}.','zh-CN':'最多选择{n}张，已选{selected}张。',vi:'Chọn tối đa {n} lá. Đã chọn: {selected}.'},
 legacyTitle:{en:'Your saved journey uses the previous rules','zh-CN':'你的存档使用旧版规则',vi:'Hành trình đã lưu dùng luật phiên bản trước'},
 legacyBody:{en:'Continue it in the preserved version, or begin a new life under the revised rules. Your original save stays intact in either case. Old seeds reproduce only their original rules version.','zh-CN':'可以进入保留的旧版本继续修行，或按新规则开启一生。两种选择均保留原始存档。旧种子只能在对应旧规则下复现。',vi:'Tiếp tục trong phiên bản được giữ lại hoặc bắt đầu kiếp mới theo luật đã sửa. Dữ liệu gốc được giữ nguyên trong cả hai trường hợp. Hạt giống cũ chỉ tái hiện đúng phiên bản luật gốc.'},
 legacyContinue:{en:'Continue previous version','zh-CN':'继续旧版道途',vi:'Tiếp tục phiên bản trước'},
 legacyNew:{en:'Preserve save & begin revised version','zh-CN':'保留存档并开始新版',vi:'Giữ bản lưu và bắt đầu phiên bản mới'},
 legacyExport:{en:'Download original save','zh-CN':'下载原始存档',vi:'Tải bản lưu gốc'},
 legacyFailure:{en:'The original save could not be archived. Nothing has been replaced.','zh-CN':'无法归档原始存档，尚未替换任何数据。',vi:'Không thể lưu trữ bản gốc. Chưa thay thế dữ liệu nào.'},
 snapshotContinuation:{en:'This saved journey will continue from its current position under the revised rules. Completed outcomes stay unchanged; the original snapshot is archived before the next save. Its earlier actions cannot be reproduced with the new rules.','zh-CN':'这段道途将从当前进度按新规则继续，已结算的结果保持不变。下次保存前会归档原始存档；此前行动不能按新规则重新复现。',vi:'Hành trình tiếp tục từ vị trí hiện tại theo luật đã sửa. Kết quả đã giải quyết được giữ nguyên; bản gốc được lưu trữ trước lần lưu tiếp theo. Không thể tái hiện các hành động trước đó bằng luật mới.'},
 basicStart:{en:'Five Strikes. Five Defenses. Two teachings. The rest is yours to write.','zh-CN':'五张打击，五张防御，两门道术。此后的路，由你书写。',vi:'Năm Đả Kích. Năm Phòng Ngự. Hai thuật pháp. Phần còn lại do bạn viết nên.'},
 mortal:{en:'THE MORTAL JOURNEY','zh-CN':'凡尘道途',vi:'HÀNH TRÌNH PHÀM NHÂN'},
 summonTurn:{en:'Acts at your turn end. Commands grant separate actions.','zh-CN':'在你的回合结束时行动。号令可使其额外行动。',vi:'Hành động cuối lượt của bạn. Mệnh lệnh cho hành động riêng.'},
 summonCounter:{en:'Counters when hurt. Commands grant separate actions.','zh-CN':'受伤时反击。号令可使其额外行动。',vi:'Phản công khi bị thương. Mệnh lệnh cho hành động riêng.'},
 summonArmor:{en:'Acts when Armor breaks. Commands grant separate actions.','zh-CN':'护甲击破时行动。号令可使其额外行动。',vi:'Hành động khi Giáp vỡ. Mệnh lệnh cho hành động riêng.'},
 inspectHint:{en:'Inspect for keywords, rules type and current modifiers.','zh-CN':'查看关键词、规则类型和当前修正。',vi:'Xem từ khóa, loại theo luật và các hiệu chỉnh hiện tại.'},
 breakthroughPackage:{en:'Realm advanced · +{hp} maximum HP · {energy} maximum Dao Yuan · +{gold} spirit stones','zh-CN':'境界提升 · 生命上限+{hp} · 道元上限{energy} · 获得{gold}灵石',vi:'Tăng cảnh giới · +{hp} HP tối đa · {energy} Đạo Nguyên tối đa · +{gold} linh thạch'},
 paidOnce:{en:'These realm rewards have already been granted.','zh-CN':'上述境界奖励已发放。',vi:'Các phần thưởng cảnh giới này đã được trao.'},
 discoveredCards:{en:'Discovered techniques','zh-CN':'已发现术法',vi:'Thuật pháp đã khám phá'},
 typeHint:{en:'Presentation role and rules type are shown separately. Strength applies to Attack hits, not every damage effect.','zh-CN':'功能定位与规则类型分开显示。力量只强化攻击伤害段，并非所有伤害效果。',vi:'Vai trò hiển thị tách biệt với loại theo luật. Sức Mạnh tăng từng đòn Tấn công, không tăng mọi hiệu ứng sát thương.'},
 sourceValues:{en:'Base definition','zh-CN':'基础效果',vi:'Hiệu ứng gốc'},
 currentValues:{en:'Current combat values','zh-CN':'当前战斗数值',vi:'Giá trị hiện tại trong trận'},
 noStats:{en:'No permanent stat bonuses.','zh-CN':'没有永久属性加成。',vi:'Không có chỉ số cộng vĩnh viễn.'},
 confirmNew:{en:'Begin another life?','zh-CN':'开启新的一生？',vi:'Bắt đầu kiếp khác?'},
 confirmNewHint:{en:'Your current life will end and remain in your history. Then a new journey begins.','zh-CN':'当前一生将结束并保留在修行记录中，随后开启新的道途。',vi:'Kiếp hiện tại sẽ kết thúc và được giữ trong lịch sử. Sau đó bắt đầu hành trình mới.'},
 restChoice:{en:'Choose one action. Inspection leaves both choices available.','zh-CN':'只能执行一个行动，查看预览不会消耗机会。',vi:'Chỉ thực hiện một hành động. Xem trước không tiêu lượt.'},
 unavailable:{en:'Unavailable','zh-CN':'当前不可用',vi:'Chưa khả dụng'},
 rewardCount:{en:'Five possibilities · learn at most one','zh-CN':'五种可能 · 最多领悟一张',vi:'Năm lựa chọn · nhận tối đa một lá'},
 previewTarget:{en:'Target-specific Armor, Qi and Vulnerable are resolved after you select a target.','zh-CN':'选定目标后，预览会计入其护甲、罡气与易伤。',vi:'Sau khi chọn mục tiêu, xem trước sẽ tính Giáp, Hộ Thể Cương Khí và Dễ Tổn Thương của mục tiêu.'}
} satisfies Record<string,Text>;
export function ui(locale:Locale,key:keyof typeof uiCopy,vars:Record<string,string|number>={}){return uiCopy[key][locale].replace(/\{(\w+)\}/g,(_,k)=>String(vars[k]??`{${k}}`));}
