'use client';
import { useState } from 'react';
import { CARDS } from '@/game/content';
import { DAO_ENCYCLOPEDIA, KEYWORD_GLOSSARY } from '@/game/encyclopedia';
import { ui } from '@/game/ui-copy';
import { tr } from '@/game/i18n';
import type { CardInstance, Locale, Text } from '@/game/types';
import { MechanicIcon } from './MechanicIcon';
import { Card } from './Card';
import { CardInspection } from './CardInspection';
const text=(en:string,zh:string,vi:string):Text=>({en,'zh-CN':zh,vi});
const lessons=[
 {title:text('Read the turn','看懂回合','Đọc tình thế lượt'),body:text('Read the enemy Intent first. Spend Dao Yuan on attacks or protection. A base Strike deals 5; a base Defense gives 5 Armor. Armor clears at your next turn start.','先看敌人意图，再分配道元用于攻击或防护。基础打击造成5伤害，基础防御给予5护甲。护甲在你的下回合开始时清除。','Đọc Ý Định của địch trước. Dùng Đạo Nguyên để tấn công hoặc bảo vệ. Đả Kích cơ bản gây 5 sát thương; Phòng Ngự cơ bản cho 5 Giáp. Giáp xóa khi lượt tiếp theo của bạn bắt đầu.'),question:text('Defense gives you…','防御给予你……','Phòng Ngự cho bạn…'),answers:[text('5 Armor','5护甲','5 Giáp'),text('5 HP','5生命','5 HP')],correct:0,feedback:text('Armor absorbs external damage; it does not heal HP.','护甲吸收外部伤害，不会回复生命。','Giáp hấp thụ sát thương bên ngoài; không hồi HP.')},
 {title:text('Build a sequence','让牌相互配合','Tạo chuỗi phối hợp'),body:text('Wisdom finds and recovers cards; its Hidden Schemes reward Active Discard. Wind rewards this turn’s play order. Cross-Path builds are always allowed. Inspect a card to see its exact condition.','智道负责找牌与回收，暗谋奖励主动弃牌；风道奖励本回合的出牌顺序。始终允许兼修。查看卡牌可读到精确触发条件。','Trí Đạo tìm và thu hồi bài; Ám Kế thưởng cho Chủ Động Bỏ Bài. Phong Đạo thưởng cho thứ tự dùng bài trong lượt. Luôn được phối hợp nhiều Đạo. Xem lá bài để biết điều kiện chính xác.'),question:text('Natural end-turn discard triggers Hidden Schemes?','回合结束的自然弃牌会触发暗谋吗？','Bỏ bài tự nhiên cuối lượt có kích Ám Kế không?'),answers:[text('Yes','会','Có'),text('No','不会','Không')],correct:1,feedback:text('Explicit player or enemy discards qualify. Natural discard and overflow do not.','玩家或敌人明确造成的弃牌符合条件，自然弃牌与溢出不符合。','Bỏ bài do người chơi hoặc địch yêu cầu mới tính. Bỏ tự nhiên và tràn tay không tính.')},
 {title:text('Prepare for a Tribulation','准备渡劫','Chuẩn bị vượt kiếp'),body:text('Rest heals up to 25% maximum HP, or upgrades one card. Previewing spends nothing. The first four major breakthroughs can offer a Divine Ability. The fifth Tribulation ends the run in Ascension.','歇脚处可回复最多25%生命上限，或升品一张卡牌。预览不消耗机会。前四次大境界突破可选择神通；第五次天劫完成飞升并结束本局。','Điểm nghỉ hồi tối đa 25% HP tối đa hoặc nâng cấp một lá. Xem trước không tiêu lượt. Bốn lần đột phá lớn đầu có thể cho Thần Thông. Thiên kiếp thứ năm kết thúc lượt chơi bằng Phi Thăng.'),question:text('Does reaching the fifth realm automatically finish your journey?','抵达第五境界就自动结束道途吗？','Đạt cảnh giới thứ năm có tự hoàn thành hành trình không?'),answers:[text('Yes','是','Có'),text('No, a final Tribulation remains','否，仍须渡过最终天劫','Không, vẫn còn thiên kiếp cuối')],correct:1,feedback:text('Read the warning and prepare. Death is final for this life. Meta progression unlocks content, never permanent combat stats.','读懂预警并做好准备。死亡永久结束此生。局外成长解锁内容，不增加永久战斗属性。','Đọc cảnh báo và chuẩn bị. Cái chết chấm dứt kiếp này. Tiến trình ngoài trận mở nội dung, không tăng chỉ số chiến đấu vĩnh viễn.')}
];
const lore=[
 {unlock:'tribulation-lore',title:text('The first answer','初次应天','Lời đáp đầu tiên'),body:text('The old masters called thunder a question. Between two strikes you found a pause. Within that pause, one small decision became a path. The heavens did not soften. You learned where to stand.','旧日师长说，天雷是一道问。你在两击之间找到了一次停顿。就在那一息里，一个微小的决定成了一条路。天劫未曾减弱，只是你终于知道该立在何处。','Các bậc thầy gọi sấm là một câu hỏi. Giữa hai đòn, bạn tìm thấy khoảng lặng. Trong khoảng lặng ấy, một quyết định nhỏ trở thành con đường. Trời cao không dịu đi. Bạn đã học được nơi cần đứng.')},
 {unlock:'spirit-realm-lore',title:text('Beyond the last cloud','最后一重云外','Bên kia tầng mây cuối'),body:text('At the summit, the Human Realm grew quiet. Blade, seed and borrowed breath had carried a mortal life as far as they could. Beyond the clouds, another shore glimmered. This Human Realm journey is complete; the farther world remains a story.','登顶之时，人界忽然安静下来。剑、种子，还有一路借来的气息，已将凡人一生送到此处。云外依稀有另一岸。本次人界修行已完成，更远的世界仍留在故事中。','Trên đỉnh núi, Nhân Giới trở nên yên lặng. Lưỡi kiếm, hạt giống và hơi thở vay mượn đã đưa kiếp phàm nhân đi xa nhất có thể. Bên kia mây, bờ khác le lói. Hành trình Nhân Giới này đã hoàn tất; thế giới xa hơn vẫn là câu chuyện.')}
];
export function FieldGuide({locale,unlocks,discovered=[]}:{locale:Locale;unlocks:string[];discovered?:string[]}){
 const [tab,setTab]=useState('start'),[lesson,setLesson]=useState(0),[answer,setAnswer]=useState<number|null>(null),[search,setSearch]=useState(''),[inspect,setInspect]=useState<CardInstance|null>(null);
 const current=lessons[lesson];
 return <div className="dao-encyclopedia"><nav className="encyclopedia-tabs"><button aria-pressed={tab==='start'} onClick={()=>setTab('start')}>{ui(locale,'beginner')}</button><button aria-pressed={tab==='paths'} onClick={()=>setTab('paths')}>{tr(locale,'allPaths')}</button><button aria-pressed={tab==='keywords'} onClick={()=>setTab('keywords')}>{ui(locale,'keywords')}</button></nav>
 {tab==='start'?<div className="field-guide"><nav className="lesson-tabs">{lessons.map((l,i)=><button key={i} aria-pressed={lesson===i} onClick={()=>{setLesson(i);setAnswer(null);}}>{i+1}. {l.title[locale]}</button>)}</nav><h3>{current.title[locale]}</h3><p>{current.body[locale]}</p><fieldset><legend>{current.question[locale]}</legend>{current.answers.map((a,i)=><button key={i} aria-pressed={answer===i} onClick={()=>setAnswer(i)}>{a[locale]}</button>)}{answer!==null&&<p role="status">{answer===current.correct?'✓ ':''}{current.feedback[locale]}</p>}</fieldset>{lore.filter(l=>unlocks.includes(l.unlock)).map(l=><details key={l.unlock}><summary>{l.title[locale]}</summary><p>{l.body[locale]}</p><small>{ui(locale,'noStats')}</small></details>)}</div>:
 tab==='paths'?<div className="path-reference">{DAO_ENCYCLOPEDIA.map(path=><details key={path.id}><summary><MechanicIcon id={path.id}/>{path.name[locale]}</summary><p>{path.description[locale]}</p><p>{path.playPattern[locale]}</p>{path.archetypes.map(archetype=><div key={archetype.id}><h4>{archetype.name[locale]}</h4><p>{archetype.description[locale]}</p></div>)}<p>{path.crossPath[locale]}</p><h4>{ui(locale,'discoveredCards')}</h4><div className="reference-cards">{discovered.filter(id=>CARDS[id]?.path===path.id).map(id=>{const card:CardInstance={uid:id,defId:id,grade:0,retained:0};return <Card key={id} card={card} locale={locale} onInspect={()=>setInspect(card)} onClick={()=>setInspect(card)}/>;})}</div></details>)}</div>:
 <div className="keyword-reference"><input aria-label={tr(locale,'search')} placeholder={tr(locale,'search')} value={search} onChange={e=>setSearch(e.target.value)}/>{Object.values(KEYWORD_GLOSSARY).filter(k=>`${k.name[locale]} ${k.description[locale]}`.toLowerCase().includes(search.toLowerCase())).map(k=><details key={k.id}><summary><MechanicIcon id={k.id}/>{k.name[locale]}</summary><p>{k.description[locale]}</p></details>)}</div>}
 {inspect&&<CardInspection card={inspect} locale={locale} onClose={()=>setInspect(null)}/>}
 </div>;
}
