'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowRight, BookOpen, ChevronLeft, Compass, Crown, Flame, Heart, Layers3, Leaf, Moon, Mountain, ScrollText, Settings2, Shield, Sparkles, X } from 'lucide-react';
import { CARDS, PATHS, REALMS } from '@/game/content';
import { describeCard, describeCombatEvent, describeEnemyIntent, enemyIntentThreat, describePower, enemyAttackValue, endTurn, playCard, validateCardPlay, powerName, previewCard, resolveChoice } from '@/game/combat';
import { buy, canUpgrade, recordActiveTime, stageIndex, restPreview, getPendingProgression, acknowledgeCompatibility, acknowledgeProgression, continueBreakthrough, chooseEvent, chooseStarting, commitCombat, enterNode, eventDisabled, EVENTS, leaveMerchant, newRun, NODE_NAMES, price, retire, salePrice, sell, STAGES, takeReward, updateMeta, upgradeCost, type Run } from '@/game/run';
import { STATUS_NAMES, tr, type CopyKey } from '@/game/i18n';
import { STATUS_HELP, ENEMY_PORTRAIT } from '@/game/status-help';
import artIndex from '@/game/art-index.json';
import { GameAudio } from '@/game/audio';
import { archiveLegacyAndStartFresh, LEGACY_CONTINUE_URL, type Settings } from '@/game/save';
import type { CardInstance, CombatEvent, Locale, Status, TidalState, Unit } from '@/game/types';
import { Card } from './Card';
import { FieldGuide } from './FieldGuide';
import { DeckBrowser } from './DeckBrowser';
import { BattleVfx } from './BattleVfx';
import { Dialog } from './Dialog';
import { commitSave, reloadSave, useGameSave } from './store';
import { ui } from '@/game/ui-copy';
import { cardTarget, targetInstruction, targetsEnemies } from '@/game/card-view';
import { gradeLabel, type GradeDisplay } from '@/game/grades';
import { GradeContext } from './GradeContext';
import { MechanicIcon } from './MechanicIcon';
import { Tooltip } from './Tooltip';
import { RoadMap } from './RoadMap';
import { Progression } from './Progression';
import { CardInspection } from './CardInspection';
import { TransactionDialog, type Service } from './Transactions';

type Screen='menu'|'game'|'collection'|'history';
type Overlay='guide'|'settings'|'deck'|'draw'|'discard'|'exhaust'|'log'|null;
const isTerminal=(run:Run)=>run.phase==='dead'||run.phase==='ascended';

function Statuses({unit,locale}:{unit:Unit;locale:Locale}){return <div className="statuses">{Object.entries(unit.statuses).filter(([,v])=>v&&v>0).map(([key,value])=><Tooltip key={key} locale={locale} label={<><MechanicIcon id={key}/><b>{value}</b><span className="sr-only">{STATUS_NAMES[key as Status][locale]}</span></>}><h3>{STATUS_NAMES[key as Status][locale]} · {value}</h3><p>{STATUS_HELP[key as Status][locale]}</p></Tooltip>)}</div>;}
function Portrait({art,entityId='wanderer',large=false}:{art:number;entityId?:string;large?:boolean}){const url=(artIndex as Record<string,string>)[entityId];return <div aria-hidden="true" className={`portrait ${large?'hero-portrait':''}`} style={url?{backgroundImage:`url(${url})`,backgroundSize:'cover',backgroundPosition:'center'}:{backgroundPosition:`${art%3*50}% ${Math.floor(art/3)*100}%`}}/>;}
function LifeBar({unit,locale}:{unit:Unit;locale:Locale}){return <div className="life-bar" aria-label={`${tr(locale,'hp')} ${unit.hp}/${unit.maxHp}`}><div style={{width:`${unit.hp/unit.maxHp*100}%`}}/><span><Heart size={12}/>{unit.hp} / {unit.maxHp}</span>{unit.armor>0&&<b className="armor-badge"><Shield size={13}/>{unit.armor}</b>}</div>;}
function TidalOptions({locale,onChoose,selected}:{locale:Locale;onChoose:(state:TidalState)=>void;selected?:TidalState|null}){return <div className="tidal-options">{(['rising','tranquil','raging'] as const).map((state,i)=><button className={`choice-tile ${selected===state?'chosen':''}`} key={state} onClick={()=>onChoose(state)}><span className="tidal-glyph">{['◒','≋','◓'][i]}</span><strong>{tr(locale,state)}</strong><p>{tr(locale,`${state}Hint`)}</p></button>)}</div>;}

export default function Game(){
 const {data,error,busy}=useGameSave();const [screen,setScreen]=useState<Screen>('menu');const [overlay,setOverlay]=useState<Overlay>(null);const [inspect,setInspect]=useState<CardInstance|null>(null);const [selected,setSelected]=useState<string|null>(null);const [selectedAt,setSelectedAt]=useState<{actions:number;combatKey:string}|null>(null);const [choiceIds,setChoiceIds]=useState<string[]>([]);const [endTidal,setEndTidal]=useState(false);const [pathFilter,setPathFilter]=useState('all');const [search,setSearch]=useState('');const [confirm,setConfirm]=useState<{kind:'sell'|'retire'|'new';card?:CardInstance}|null>(null);const [service,setService]=useState<Service|null>(null);const [toast,setToast]=useState('');const [flash,setFlash]=useState('');
 const [feedback,setFeedback]=useState<CombatEvent[]>([]);
 const [dragPoint,setDragPoint]=useState<{uid:string;x:number;y:number}|null>(null);
 const touchDrag=useRef<{uid:string;pointerId:number;x:number;y:number;moved:boolean;at:number;combatKey:string}|null>(null);const suppressClick=useRef(false);
 const activeTime=useRef(0);const audio=useRef<GameAudio|null>(null);const actionLock=useRef(false);const combatArea=useRef<HTMLDivElement>(null);
 const locale=data?.settings.locale??'en',run=data?.run??null,combat=run?.combat??null;const combatKey=run&&combat?`${run.id}:${run.current?.id}:${combat.seed}`:'';const selectedCard=combat&&selectedAt?.combatKey===combatKey&&selectedAt.actions===combat.actions.length?combat.hand.find(c=>c.uid===selected)??null:null;const t=useCallback((key:CopyKey,vars?:Record<string,string|number>)=>tr(locale,key,vars),[locale]);
 useEffect(()=>{document.documentElement.lang=locale;},[locale]);
 useEffect(()=>{audio.current=new GameAudio();return()=>audio.current?.close();},[]);
 useEffect(()=>{if(data)audio.current?.volume(data.settings.music,data.settings.sfx);},[data]);
 useEffect(()=>{let prior=performance.now();const timer=setInterval(()=>{const now=performance.now();if(screen==='game'&&run&&!isTerminal(run)&&document.visibilityState==='visible')activeTime.current+=Math.min(2000,now-prior);prior=now;},1000);return()=>clearInterval(timer);},[screen,run]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);},[toast]);
 const settings=async(patch:Partial<Settings>)=>{if(data)await commitSave({...data,settings:{...data.settings,...patch}});};
 const saveRun=useCallback(async(next:Run)=>{if(!data||busy||error||actionLock.current||next===run)return;actionLock.current=true;try{let elapsed=Math.round(activeTime.current);activeTime.current=0;let clocked=run??next;while(elapsed>0){const tick=Math.min(60000,elapsed);clocked=recordActiveTime(clocked,tick);elapsed-=tick;}const timed={...next,activeMs:Math.max(next.activeMs,clocked.activeMs)};await commitSave({...data,run:timed,meta:updateMeta(data.meta,timed,Date.now())});}finally{actionLock.current=false;}},[data,busy,error,run]);
 async function start(replaceActive=false){
  if(!data||busy||error||actionLock.current)return;
  actionLock.current=true;
  try{
   let base=data;
   if(replaceActive&&run&&!isTerminal(run)){
    const retired=retire(run),saved=await commitSave({...base,run:retired,meta:updateMeta(base.meta,retired,Date.now())});
    if(!saved)return;base=saved;
   }
   void audio.current?.unlock(base.settings.music,base.settings.sfx).catch(()=>{});
   const next=newRun(crypto.getRandomValues(new Uint32Array(1))[0]||1,Date.now());
   const saved=await commitSave({...base,run:next,meta:updateMeta(base.meta,next,Date.now())});
   if(!saved)return;activeTime.current=0;setScreen('game');setSelected(null);setConfirm(null);audio.current?.play('reward');
  }finally{actionLock.current=false;}
 }
 const baseInteractionBlocked=busy||!!error||!!overlay||!!inspect||!!confirm||!!service||!!combat?.choice||!!combat?.pending?.length||combat?.phase!=='player';
 const interactionBlocked=baseInteractionBlocked||endTidal;
 async function perform(uid:string,target?:string){
  if(!run||run.phase!=='combat'||!combat||interactionBlocked||actionLock.current)return;
  const reason=validateCardPlay(combat,uid,target);
  if(reason){setSelected(null);setToast(reason[locale]);return;}
  const card=combat.hand.find(c=>c.uid===uid);if(!card)return;
  const next=playCard(combat,uid,target);if(next===combat)return;
  audio.current?.play(CARDS[card.defId].exhaust?'exhaust':CARDS[card.defId].kind==='attack'?'hit':'card');
  setFlash(CARDS[card.defId].path);setFeedback(next.events.slice(combat.events.length));
  await saveRun(commitCombat(run,next));setSelected(null);setChoiceIds([]);setToast('');
 }
 function selectCard(card:CardInstance){
  if(!combat||interactionBlocked||actionLock.current||suppressClick.current)return;
  setSelected(selectedCard?.uid===card.uid?null:card.uid);setSelectedAt({actions:combat.actions.length,combatKey});
 }
 function pickupCard(card:CardInstance){if(combat&&!interactionBlocked){setSelected(card.uid);setSelectedAt({actions:combat.actions.length,combatKey});}}
 function doubleClickCard(card:CardInstance){
  if(!combat||interactionBlocked||suppressClick.current)return;
  const target=cardTarget(card);
  if(target==='enemy'){pickupCard(card);return;}
  void perform(card.uid,target==='self'?combat.player.id:undefined);
 }
 function cancelDrag(){setSelected(null);setDragPoint(null);touchDrag.current=null;}
 function touchStart(card:CardInstance,e:React.PointerEvent<HTMLButtonElement>){
  if(e.pointerType==='mouse'||!combat||interactionBlocked)return;
  touchDrag.current={uid:card.uid,pointerId:e.pointerId,x:e.clientX,y:e.clientY,moved:false,at:combat.actions.length,combatKey};
  e.currentTarget.setPointerCapture(e.pointerId);
 }
 function touchMove(e:React.PointerEvent<HTMLButtonElement>){
  const gesture=touchDrag.current;if(!gesture||gesture.pointerId!==e.pointerId)return;
  if(!gesture.moved&&Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)<10)return;
  gesture.moved=true;e.preventDefault();setSelected(gesture.uid);setSelectedAt({actions:gesture.at,combatKey:gesture.combatKey});setDragPoint({uid:gesture.uid,x:e.clientX,y:e.clientY});
  if(e.clientY<60)window.scrollBy(0,-22);else if(e.clientY>window.innerHeight-60)window.scrollBy(0,22);
 }
 function touchRelease(e:React.PointerEvent<HTMLButtonElement>){
  const gesture=touchDrag.current;if(!gesture||gesture.pointerId!==e.pointerId)return;
  touchDrag.current=null;setDragPoint(null);
  if(!gesture.moved)return;
  e.preventDefault();suppressClick.current=true;setTimeout(()=>{suppressClick.current=false;},800);setSelected(null);
  const target=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-combat-target]')?.dataset.combatTarget;
  if(target&&combatKey===gesture.combatKey&&combat?.actions.length===gesture.at)void perform(gesture.uid,target);
 }
 async function finishTurn(tidal?:TidalState){if(!run||run.phase!=='combat'||!combat||baseInteractionBlocked||(endTidal&&!tidal)||actionLock.current)return;if(combat.tidal&&!tidal){setEndTidal(true);return;}audio.current?.play('turn');setFlash('turn');const next=endTurn(combat,tidal);setFeedback(next.events.slice(combat.events.length));await saveRun(commitCombat(run,next));setSelected(null);setEndTidal(false);setChoiceIds([]);}
 useEffect(()=>{function key(e:KeyboardEvent){
  if((e.target as HTMLElement).matches('input,select,textarea')||interactionBlocked||screen!=='game'||run?.phase!=='combat')return;
  if(e.code==='Escape'){cancelDrag();return;}
  if(e.key.toLowerCase()==='e'){e.preventDefault();void finishTurn();}
  const index=e.key==='0'?9:Number(e.key)-1;
  if(index>=0&&index<10&&combat?.hand[index]){e.preventDefault();selectCard(combat.hand[index]);}
  if(e.key==='Enter'&&selectedCard&&!(e.target as HTMLElement).closest('button,[role="button"]')){
   e.preventDefault();doubleClickCard(selectedCard);
  }
 }window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 function exportDiagnostic(){const payload={exportedAt:new Date().toISOString(),data,storage:Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('heavenward')).map(k=>[k,localStorage.getItem(k)]))};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='heavenward-diagnostic.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function reward(uid:string,shop=false){if(!run)return;audio.current?.play('reward');void saveRun(shop?buy(run,uid):takeReward(run,uid));}
 function showCard(c:CardInstance){setInspect(c);}
 if(!data&&!error)return <main className="loading-world"><span className="seal">天</span><p>HEAVENWARD</p></main>;
 if(!data&&error==='compatibility')return <main className="error-page"><h1>{ui(locale,'legacyTitle')}</h1><p>{ui(locale,'legacyBody')}</p>{toast&&<p role="alert">{toast}</p>}<div className="button-row"><a className="primary-button" href={LEGACY_CONTINUE_URL}>{ui(locale,'legacyContinue')}</a><button onClick={exportDiagnostic}>{ui(locale,'legacyExport')}</button><button onClick={()=>{try{archiveLegacyAndStartFresh(localStorage,'start-new-revision');reloadSave();}catch{setToast(ui(locale,'legacyFailure'));}}}>{ui(locale,'legacyNew')}</button></div></main>;
 if(!data)return <main className="error-page"><h1>{t('corrupt')}</h1><div className="button-row"><button onClick={exportDiagnostic}>{t('export')}</button><button onClick={reloadSave}>{t('retry')}</button></div></main>;

 const title=(eyebrow:string,heading:string,desc?:string)=><div className="scene-title"><span className="eyebrow">{eyebrow}</span><h1>{heading}</h1>{desc&&<p>{desc}</p>}<div className="title-rule"><span>◆</span></div></div>;
 const terminal=run&&isTerminal(run);
 const canResume=run&&(!terminal||getPendingProgression(run)?.view==='receipt');
 const progression=run?getPendingProgression(run):null;
 const majorReceipt=progression?.kind==='major'&&progression.view==='receipt'?progression:null;
 const endSummary=terminal?data.meta.history.find(h=>h.id===run.id):null;
 return <GradeContext.Provider value={data.settings.gradeDisplay}><main onClickCapture={e=>{if(e.detail>1){e.preventDefault();e.stopPropagation();}}} onKeyDownCapture={e=>{if(e.repeat){e.preventDefault();e.stopPropagation();}}} className={`world locale-${locale} ${data.settings.reducedMotion?'reduced-motion':''} screen-${screen} ${screen==='game'&&run?.phase==='combat'?'in-combat':''}`} style={{'--motion-speed':data.settings.speed,'--cardback':data.settings.cardback==='ink-cardback'?'#0d253a':data.settings.cardback==='ascendant-cardback'?'#67502c':'#162c2c'} as React.CSSProperties}>
  <div className="world-art" aria-hidden="true"/><div className="world-vignette" aria-hidden="true"/>
  <header className="topbar"><button className="wordmark" onClick={()=>setScreen('menu')} aria-label={t('menu')}><span className="brand-seal">天</span><span>HEAVENWARD</span></button>
  {run&&screen==='game'&&!isTerminal(run)&&<div className="run-resources"><span className="realm-mini"><Mountain size={17}/>{REALMS[run.realm].name[locale]} <small>{STAGES[stageIndex(run)][locale]}</small></span><span className="health-resource"><Heart size={16}/>{run.hp}<small>/{run.maxHp}</small></span><span className="gold-resource"><MechanicIcon id="basic"/>{run.gold}</span><button onClick={()=>setOverlay('deck')}><Layers3 size={16}/>{run.deck.length}</button></div>}
  <nav className="top-actions"><div className="language-switch" aria-label={t('locale')}><button aria-pressed={locale==='en'} onClick={()=>void settings({locale:'en'})}>EN</button><span>/</span><button aria-pressed={locale==='zh-CN'} onClick={()=>void settings({locale:'zh-CN'})}>简中</button><span>/</span><button aria-pressed={locale==='vi'} onClick={()=>void settings({locale:'vi'})}>VI</button></div><button className="icon-button" onClick={()=>setOverlay('settings')} aria-label={t('settings')}><Settings2 size={19}/></button></nav></header>
  {error&&<div className="save-error" role="alert"><span>{t('saveError')}</span><button onClick={exportDiagnostic}>{t('export')}</button><button onClick={reloadSave}>{t('retry')}</button></div>}
  {screen==='menu'&&<section className="main-menu"><div className="menu-copy"><div className="eyebrow"><span/> {t('human')} <span/></div><h1>{locale==='zh-CN'?<>问<span>天</span></>:<>HEAVEN<span>WARD</span></>}</h1><p className="menu-subtitle">{t('life')}</p><div className="menu-rule"/><nav className="menu-options">{canResume&&<button className="primary-button" onClick={()=>{setScreen('game');void audio.current?.unlock(data.settings.music,data.settings.sfx).catch(()=>{});}}><span>{t('continue')}</span><ArrowRight size={19}/></button>}<button className={canResume?'menu-button':'primary-button'} onClick={()=>canResume?setConfirm({kind:'new'}):void start()}><span>{t('newRun')}</span><ArrowRight size={18}/></button><button className="menu-button" onClick={()=>setScreen('collection')}><BookOpen size={17}/>{t('collection')}</button><button className="menu-button" onClick={()=>setOverlay('guide')}><Compass size={17}/>{ui(locale,'encyclopedia')}</button><button className="menu-button" onClick={()=>setScreen('history')}><ScrollText size={17}/>{t('history')}</button></nav><div className="menu-footer"><span>{t('noCloud')}</span><span>{t('human')} · 0.3</span></div></div><div className="menu-poem" aria-hidden="true"><span>一生修行</span><span>一念问天</span></div><div className="chapter-mark"><span>壹</span><div>{t('human')}<small>{ui(locale,'mortal')}</small></div></div></section>}

  {screen==='game'&&run&&<div className={`game-stage phase-${run.phase}`}>
   {run.compatibility&&!run.compatibility.noticeAcknowledged&&<aside className="compatibility-notice" role="status"><p>{ui(locale,'snapshotContinuation')}</p><button className="secondary-button" onClick={()=>void saveRun(acknowledgeCompatibility(run))}>{t('continue')}</button></aside>}
   {progression?.kind==='minor'&&run.phase!=='combat'&&<Progression receipt={progression} locale={locale} onContinue={()=>void saveRun(acknowledgeProgression(run,progression.id))}/>}
   {majorReceipt&&<Progression receipt={majorReceipt} locale={locale} onContinue={()=>void saveRun(continueBreakthrough(run,majorReceipt.id))}/>}
   {run.phase==='starting'&&<section className="choice-scene">{title(t('round',{n:run.startingRound+1}),t('starting'),t('startingHint'))}<div className="offer-row starting-offers">{run.offers.map(c=><div className="offer" key={c.uid}><Card card={c} locale={locale} onClick={()=>showCard(c)} onInspect={()=>showCard(c)}/><button className="card-action" onClick={()=>void saveRun(chooseStarting(run,c.uid))}>{t('choose')}<ArrowRight size={15}/></button></div>)}</div><p className="scene-note">{ui(locale,'basicStart')}</p></section>}
   {run.phase==='road'&&<RoadMap run={run} locale={locale} onEnter={id=>void saveRun(enterNode(run,id))}/>}

   {run.phase==='combat'&&combat&&<section className={`battle ${selectedCard?'targeting':''}`} ref={combatArea}>
    <BattleVfx events={feedback} speed={data.settings.speed} reduced={data.settings.reducedMotion}/><div className="battle-heading"><span className="eyebrow">{NODE_NAMES[run.current?.kind??'combat'][locale]}</span><h1>{combat.enemies[0]?.name[locale]}</h1><div className="turn-label"><span className="turn-dot"/>{t('turn',{n:combat.turn})}</div></div>
    {data.settings.tutorial&&combat.turn<=2&&run.stats.combats===0&&<div className="tutorial"><Sparkles size={16}/><p>{t(combat.turn===1?'tutorial1':'tutorial2')}</p><button className="icon-button" aria-label={t('close')} onClick={()=>void settings({tutorial:false})}><X size={15}/></button></div>}
    <div className={`battlefield flash-${flash}`} key={`${combat.turn}-${combat.actions.length}`}>
     <div className="player-side"><div data-combat-target={combat.player.id} className={`cultivator ${selectedCard&&cardTarget(selectedCard!)==='self'?'valid-target':''}`} role="button" tabIndex={0} aria-label={ui(locale,'player')} onClick={()=>selectedCard&&void perform(selectedCard.uid,combat.player.id)} onKeyDown={e=>{if(e.target===e.currentTarget&&e.key==='Enter'&&selectedCard)void perform(selectedCard.uid,combat.player.id);}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void perform(e.dataTransfer.getData('text/heavenward-card'),combat.player.id);}}><div className="unit-name">{ui(locale,'player')}</div>{combat.tidal&&<div className={`tidal-aura tidal-${combat.tidal}`}><span>{t(combat.tidal)}</span></div>}<Portrait art={0}/><LifeBar unit={combat.player} locale={locale}/><Statuses unit={combat.player} locale={locale}/></div>
      {combat.summons.length>0&&<div className="summon-row" aria-label={t('summons')}>{combat.summons.filter(s=>s.hp>0).map(s=><div className="summon" key={s.id} title={ui(locale,s.automatic==='turnEnd'?'summonTurn':s.automatic==='counter'?'summonCounter':'summonArmor')}><div className="summon-art" aria-hidden="true" style={{backgroundImage:`url(${(artIndex as Record<string,string>)[s.defId]})`}}/><strong>{s.name[locale]}</strong><span><Heart size={11}/>{s.hp}/{s.maxHp} <MechanicIcon id="attack" size={11}/>{s.attack}</span></div>)}</div>}
      {Object.entries(combat.powers).filter(([id,v])=>v>0&&powerName(id,locale)).length>0&&<div className="powers"><Sparkles size={15}/>{Object.entries(combat.powers).filter(([id,v])=>v>0&&powerName(id,locale)).map(([id,value])=><span key={id} title={describePower(id,value,locale)}>{powerName(id,locale)} {value>1?value:''}</span>)}</div>}
     </div>
     <div className="battle-divider"><span>对</span></div><div className={`enemy-side enemies-${combat.enemies.filter(e=>e.hp>0).length}`}>
     {combat.enemies.filter(e=>e.hp>0).map(enemy=>{const preview=selectedCard&&targetsEnemies(selectedCard)?previewCard(combat,selectedCard.uid,enemy.id):null;const attack=enemy.intent.effects.filter(e=>e.op==='damage'),threat=enemyIntentThreat(combat,enemy.id);return <div role="button" tabIndex={0} onKeyDown={e=>{if(e.target===e.currentTarget&&e.key==='Enter'&&selectedCard)void perform(selectedCard.uid,enemy.id);}} data-combat-target={enemy.id} className={`enemy ${selectedCard&&targetsEnemies(selectedCard)?'valid-target':''}`} key={enemy.id} onClick={()=>selectedCard&&void perform(selectedCard.uid,enemy.id)} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';}} onDrop={e=>{e.preventDefault();const uid=e.dataTransfer.getData('text/heavenward-card');if(uid)void perform(uid,enemy.id);}} aria-label={`${enemy.name[locale]}. ${enemy.intent.name[locale]}. ${enemy.hp} ${t('hp')}`}>
       <div className={`enemy-intent intent-${enemy.intent.kind}`}><Tooltip locale={locale} label={<><MechanicIcon id={enemy.intent.kind==='attack'?'attack':enemy.intent.kind==='defend'?'defense':'energyDebt'}/>{attack.map((a,i)=><strong key={i}>{enemyAttackValue(combat,enemy.id,a)}{(a.hits??1)>1?` × ${a.hits}`:''}</strong>)}{threat.warning&&<strong className="warning-value">{ui(locale,'warningHit',{n:threat.main})}</strong>}<span>{enemy.intent.name[locale]}</span>{!threat.warning&&attack.length===0&&threat.total>0&&<strong>{ui(locale,'commandTotal',{n:threat.total})}</strong>}{threat.followups>0&&<small className="beast-threat">{ui(locale,'beastThreat',{n:threat.followupTotal,total:threat.total})}</small>}</>}><h3>{enemy.intent.name[locale]}</h3>{attack.map((a,i)=><p key={i}>{ui(locale,'rawAttack',{hits:a.hits??1,amount:enemyAttackValue(combat,enemy.id,a),total:enemyAttackValue(combat,enemy.id,a)*(a.hits??1)})}</p>)}<p>{describeEnemyIntent(combat,enemy.id,locale)}</p></Tooltip></div>
       <Portrait art={ENEMY_PORTRAIT[enemy.defId]??1} entityId={enemy.defId}/><div className="enemy-name">{enemy.name[locale]}</div><LifeBar unit={enemy} locale={locale}/><Statuses unit={enemy} locale={locale}/>
       {preview&&<div className="target-preview"><span><Heart size={13}/>−{preview.hp}</span><span><Shield size={13}/>−{preview.armor}</span>{preview.selfHp>0&&<span>{ui(locale,'self')} −{preview.selfHp}</span>}{preview.hits.length>1&&<small>{ui(locale,'damageHits')}: {preview.hits.join(' / ')}</small>}{preview.uncertain&&<small>{t('previewUnknown')}</small>}</div>}
      </div>;})}</div>
    </div>
    <div className="battle-decision"><span>{selectedCard?targetInstruction(selectedCard,locale):t('shortcuts')}</span>{selectedCard&&['none','allEnemies','randomEnemy'].includes(cardTarget(selectedCard))&&<button className="play-selected" onClick={()=>void perform(selectedCard.uid)}>{ui(locale,'playSelected')}</button>}{selectedCard&&<button onClick={()=>setSelected(null)}>{t('cancel')} <kbd>Esc</kbd></button>}<button className="text-button log-button" onClick={()=>setOverlay('log')}><ScrollText size={14}/>{t('log')}</button></div>
    <div className="hand-area"><div className="resource-well"><div className="energy-orb"><span>{combat.energy}</span><small>/{combat.maxEnergy}</small></div><span>{t('energy')}</span><button className="pile-button" onClick={()=>setOverlay('draw')}><Layers3 size={18}/><b>{combat.draw.length}</b><span>{t('draw')}</span></button></div>
     <div className={`hand-cards hand-${combat.hand.length}`} aria-label={t('hand')}>{combat.hand.map((c,i)=><div className="hand-slot" key={c.uid} style={{'--i':i,'--count':combat.hand.length} as React.CSSProperties}><span className="card-shortcut">{i===9?0:i+1}</span><Card card={c} locale={locale} combat={combat} selected={selectedCard?.uid===c.uid} onClick={()=>selectCard(c)} onDoubleClick={()=>doubleClickCard(c)} onPickup={()=>pickupCard(c)} onDragCancel={cancelDrag} gestures={{onPointerDown:e=>touchStart(c,e),onPointerMove:touchMove,onPointerUp:touchRelease,onPointerCancel:cancelDrag}} onInspect={()=>showCard(c)} draggable disabled={interactionBlocked}/></div>)}</div>
     <div className="turn-controls"><button className="end-turn" disabled={!!combat.choice||busy} onClick={()=>void finishTurn()}>{t('endTurn')}<small>E <ArrowRight size={15}/></small></button><div className="pile-pair"><button className="pile-button" onClick={()=>setOverlay('discard')}><Layers3 size={16}/><b>{combat.discard.length}</b><span>{t('discard')}</span></button><button className="pile-button" onClick={()=>setOverlay('exhaust')}><Flame size={16}/><b>{combat.exhaust.length}</b><span>{t('exhaust')}</span></button></div></div>
    </div>
   </section>}

   {!majorReceipt&&['reward','inheritance','breakthrough'].includes(run.phase)&&<section className="choice-scene reward-scene">{title(run.phase==='breakthrough'?REALMS[run.realm].name[locale]:t('human'),t(run.phase==='breakthrough'?'breakthrough':run.phase==='inheritance'?'inheritance':'victory'),t(run.rewardKind==='foundation'?'foundationHint':run.phase==='breakthrough'?'breakthroughHint':run.phase==='inheritance'?'inheritanceHint':'rewardHint',{n:run.draftRemaining}))}<div className="offer-row">{run.offers.map(c=><div className="offer" key={c.uid}><Card card={c} locale={locale} onClick={()=>showCard(c)} onInspect={()=>showCard(c)}/><button className="card-action" onClick={()=>reward(c.uid)}>{t('acquire')}<ArrowRight size={15}/></button></div>)}</div><div className="scene-actions"><button className="text-button" onClick={()=>setOverlay('deck')}><Layers3 size={16}/>{t('deck')} · {run.deck.length}</button><button className="secondary-button" onClick={()=>void saveRun(takeReward(run,null))}>{t('skip')}<ArrowRight size={16}/></button></div></section>}
   {run.phase==='merchant'&&<section className="merchant-scene">{title(ui(locale,'seller'),t('merchant'),ui(locale,'sellerLine'))}<div className="shop-tabs"><span><MechanicIcon id="basic"/> {run.gold} {t('stones')}</span><button onClick={()=>setOverlay('deck')}>{t('deck')} {run.deck.length}</button></div><div className="offer-row shop-stock">{run.offers.map(c=>{const purchased=run.shop.purchased.includes(c.uid),affordable=run.gold>=price(c);return <div className={`offer ${purchased?'purchased':''}`} key={c.uid}><Card card={c} locale={locale} onClick={()=>showCard(c)} onInspect={()=>showCard(c)}/><button className="card-action" aria-disabled={purchased||!affordable} onClick={()=>purchased?setToast(ui(locale,'purchased')):!affordable?setToast(ui(locale,'notEnough',{n:price(c)-run.gold})):reward(c.uid,true)}>{purchased?t('sold'):`${t('buy')} · ${price(c)}`}</button>{!purchased&&!affordable&&<p className="price-reason">{ui(locale,'notEnough',{n:price(c)-run.gold})}</p>}</div>;})}</div><div className="shop-services"><div><h2>{t('upgrade')}</h2><p>{t('upgradeHint')} · {run.shop.upgraded}/2</p><button className="service-button" onClick={()=>setService('upgrade')}><Flame size={20}/>{ui(locale,'chooseUpgrade')} · {upgradeCost(run)}</button></div><div><h2>{t('sell')}</h2><p>{t('saleHint',{n:REALMS[run.realm].minDeck})} · {run.shop.sold}/3</p><button className="service-button" onClick={()=>setService('sell')}><Layers3 size={20}/>{ui(locale,'chooseSale')}</button></div><button className="secondary-button" onClick={()=>void saveRun(leaveMerchant(run))}>{t('leave')}<ArrowRight size={16}/></button></div></section>}
   {run.phase==='rest'&&<section className="rest-scene">{title(t('human'),t('rest'),t('restHint'))}<div className="rest-choices">{run.current?.eventId!==99&&<button className="rest-option rest-healing" onClick={()=>setService('rest')}><Moon size={48} strokeWidth={1}/><h2>{t('heal')}</h2><p>{restPreview(run).heal?ui(locale,'healActual',{n:restPreview(run).heal}):ui(locale,'fullHealth')}</p><span>{run.hp}/{run.maxHp} <ArrowRight size={17}/> {restPreview(run).hpAfter}/{run.maxHp}</span></button>}<button className="rest-option rest-refining" onClick={()=>setService('upgrade')}><Flame size={48} strokeWidth={1}/><h2>{t('freeUpgrade')}</h2><p>{ui(locale,'previewOnly')}</p>{!run.deck.some(c=>canUpgrade(run,c))&&<small>{ui(locale,'noUpgrades')}</small>}<span>{ui(locale,'chooseUpgrade')}<ArrowRight size={17}/></span></button></div><p className="scene-note">{ui(locale,'restChoice')}</p></section>}
   {run.phase==='event'&&<section className="event-scene"><div className="event-illustration"><div className="event-moon">缘</div></div><div className="event-copy"><span className="eyebrow">{NODE_NAMES.event[locale]}</span><h1>{EVENTS[run.current?.eventId??0].name[locale]}</h1><p className="event-story">{EVENTS[run.current?.eventId??0].story[locale]}</p><div className="event-options">{EVENTS[run.current?.eventId??0].options.map((option,i)=><button key={i} disabled={eventDisabled(run,i)} onClick={()=>void saveRun(chooseEvent(run,i))}><div><strong>{option.label[locale]}</strong><p>{option.description[locale]}</p></div><ArrowRight size={18}/></button>)}</div></div></section>}
   {terminal&&!majorReceipt&&<section className={`terminal-scene ${run.phase}`}><div className="terminal-seal">{run.phase==='ascended'?<Crown size={48} strokeWidth={1}/>:<Leaf size={48} strokeWidth={1}/>}</div>{title(t('human'),t(run.phase==='ascended'?'ascended':'dead'),t(run.phase==='ascended'?'ascendedHint':'deadHint'))}<div className="run-stats"><div><small>{t('highestRealm')}</small><strong>{REALMS[run.realm].name[locale]}</strong></div>{(['combats','elites','tribulations','cards'] as const).map(key=><div key={key}><small>{t(key)}</small><strong>{run.stats[key]}</strong></div>)}</div>{endSummary&&<p className="summary-paths">{endSummary.paths.map(id=>PATHS.find(p=>p.id===id)?.name[locale]).filter(Boolean).join(' · ')}<span>{ui(locale,'activeTime',{n:Math.floor(endSummary.duration/60000)})}</span></p>}{endSummary&&run.phase==='dead'&&<p className="cause">{endSummary.cause[locale]}</p>}<div className="scene-actions"><button className="secondary-button" onClick={()=>setScreen('menu')}>{t('returnMenu')}</button><button className="primary-button" onClick={()=>void start()}>{t('newLife')}<ArrowRight size={17}/></button></div><p className="scene-note">{t('unlockHint')}</p></section>}
  </div>}

  {screen==='collection'&&<section className="collection-scene"><button className="back-link" onClick={()=>setScreen('menu')}><ChevronLeft size={17}/>{t('back')}</button>{title(t('human'),t('collection'))}<div className="collection-controls"><select aria-label={t('allPaths')} value={pathFilter} onChange={e=>setPathFilter(e.target.value)}><option value="all">{t('allPaths')}</option>{PATHS.map(p=><option value={p.id} key={p.id}>{p.name[locale]}</option>)}</select><input placeholder={t('search')} aria-label={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/><span>{data.meta.discovered.length} {t('discovered')}</span></div><div className="card-grid">{Object.values(CARDS).filter(c=>!['token','status'].includes(c.category)&&(pathFilter==='all'||c.path===pathFilter)&&`${c.name[locale]} ${describeCard({uid:c.id,defId:c.id,grade:0,retained:0},locale)}`.toLowerCase().includes(search.toLowerCase())).map(c=><div className="collection-card" key={c.id}><Card card={{uid:c.id,defId:c.id,grade:0,retained:0}} locale={locale} onClick={()=>showCard({uid:c.id,defId:c.id,grade:0,retained:0})} onInspect={()=>showCard({uid:c.id,defId:c.id,grade:0,retained:0})}/><span>{data.meta.discovered.includes(c.id)?t('discovered'):t('undiscovered')}</span></div>)}</div></section>}
  {screen==='history'&&<section className="history-scene"><button className="back-link" onClick={()=>setScreen('menu')}><ChevronLeft size={17}/>{t('back')}</button>{title(t('human'),t('history'))}{data.meta.history.length===0?<p className="empty-state">{t('noHistory')}</p>:<div className="history-list">{data.meta.history.map((h,i)=><article key={h.id}><span className="history-index">{String(data.meta.history.length-i).padStart(2,'0')}</span><div><h2>{REALMS[h.realm].name[locale]}</h2><p>{h.outcome==='ascended'?t('ascended'):h.cause[locale]}</p><p className="history-paths">{h.paths.map(id=>PATHS.find(p=>p.id===id)?.name[locale]).filter(Boolean).join(' · ')}</p><small>{t('seed')} {h.seed} · {ui(locale,h.durationKind==='legacy-wall'?'legacyTime':'activeTime',{n:Math.floor(h.duration/60000)})}</small></div><span>{h.stats.tribulations} {t('tribulations')}</span><span>{h.outcome==='ascended'?<Crown/>:<Leaf/>}</span></article>)}</div>}</section>}

  {overlay==='guide'&&<Dialog locale={locale} title={ui(locale,'encyclopedia')} wide onClose={()=>setOverlay(null)}><FieldGuide locale={locale} unlocks={data.meta.unlocks} discovered={data.meta.discovered}/></Dialog>}
  {overlay==='settings'&&<Dialog locale={locale} title={t('settings')} onClose={()=>setOverlay(null)}><div className="settings-body"><label>{t('locale')}<select value={locale} onChange={e=>void settings({locale:e.target.value as Locale})}><option value="en">English</option><option value="zh-CN">简体中文</option><option value="vi">Tiếng Việt</option></select></label><label>{ui(locale,'gradeDisplay')}<select aria-label={ui(locale,'gradeDisplay')} value={data.settings.gradeDisplay} onChange={e=>void settings({gradeDisplay:e.target.value as GradeDisplay})}>{(['numeric','letters','traditional'] as const).map(style=><option key={style} value={style}>{ui(locale,style)}</option>)}</select></label><p className="grade-scale">{Array.from({length:8},(_,i)=>gradeLabel(i,locale,data.settings.gradeDisplay)).join(' → ')}</p><p className="muted">{ui(locale,'gradeOrder')}</p><button className="secondary-button" onClick={()=>setOverlay('guide')}>{ui(locale,'encyclopedia')}</button><label>{t('music')}<input aria-label={t('music')} type="range" min="0" max="1" step=".05" value={data.settings.music} onChange={e=>void settings({music:Number(e.target.value)})}/></label><label>{t('sfx')}<input aria-label={t('sfx')} type="range" min="0" max="1" step=".05" value={data.settings.sfx} onChange={e=>void settings({sfx:Number(e.target.value)})}/></label><label>{t('speed')}<select value={data.settings.speed} onChange={e=>void settings({speed:Number(e.target.value)})}>{[.5,1,1.5,2].map(v=><option key={v} value={v}>{v}×</option>)}</select></label><label>{t('reduce')}<input type="checkbox" checked={data.settings.reducedMotion} onChange={e=>void settings({reducedMotion:e.target.checked})}/></label><label>{t('onboarding')}<input type="checkbox" checked={data.settings.tutorial} onChange={e=>void settings({tutorial:e.target.checked})}/></label><label>{t('cosmetic')}<select value={data.settings.cardback} onChange={e=>void settings({cardback:e.target.value})}><option value="default">{t('defaultBack')}</option>{data.meta.unlocks.includes('ink-cardback')&&<option value="ink-cardback">{t('inkBack')}</option>}{data.meta.unlocks.includes('ascendant-cardback')&&<option value="ascendant-cardback">{t('ascendantBack')}</option>}</select></label><p className="muted">{t('save')} · {t('noCloud')}</p><button className="secondary-button" onClick={exportDiagnostic}>{t('export')}</button><a className="secondary-button" href={LEGACY_CONTINUE_URL}>{ui(locale,'legacyContinue')}</a>{run&&!isTerminal(run)&&<button className="danger-text" onClick={()=>{setOverlay(null);setConfirm({kind:'retire'});}}>{t('retire')}</button>}</div></Dialog>}
  {overlay&&['deck','draw','discard','exhaust'].includes(overlay)&&run&&<Dialog locale={locale} title={t(overlay as 'deck'|'draw'|'discard'|'exhaust')} wide onClose={()=>setOverlay(null)}>{overlay==='draw'&&<p className="dialog-note">{t('hiddenOrder')}</p>}{overlay==='deck'&&<p className="dialog-note">{ui(locale,'noDeckMaximum')} {ui(locale,'deckMinimum',{current:run.deck.length,minimum:REALMS[run.realm].minDeck})}</p>}<DeckBrowser cards={[...(overlay==='deck'?run.deck:combat?.[overlay as 'draw'|'discard'|'exhaust']??[])].sort((a,b)=>CARDS[a.defId].name[locale].localeCompare(CARDS[b.defId].name[locale]))} locale={locale} onInspect={showCard}/></Dialog>}
  {overlay==='log'&&combat&&<Dialog locale={locale} title={t('log')} onClose={()=>setOverlay(null)}><div className="combat-log">{combat.events.slice(-80).map((event,i)=><p key={i}><span>{i+1}</span>{describeCombatEvent(event,locale,combat)}</p>)}</div></Dialog>}
  {service&&run&&<TransactionDialog key={`${service}-${run.id}`} run={run} locale={locale} service={service} onClose={()=>setService(null)} onCommit={saveRun} onInspect={showCard}/>}
  {inspect&&<CardInspection card={inspect} locale={locale} combat={run?.phase==='combat'?combat??undefined:undefined} onClose={()=>setInspect(null)}/>}
  {confirm&&<Dialog locale={locale} title={confirm.kind==='new'?ui(locale,'confirmNew'):t(confirm.kind==='sell'?'confirmSell':'confirmRetire')} onClose={()=>setConfirm(null)}><p className="dialog-note">{confirm.kind==='new'?ui(locale,'confirmNewHint'):t(confirm.kind==='sell'?'confirmSellHint':'confirmRetireHint')}</p>{confirm.card&&<p className="dialog-note">{CARDS[confirm.card.defId].name[locale]} · +{salePrice(confirm.card)} ◈</p>}<div className="scene-actions"><button className="secondary-button" onClick={()=>setConfirm(null)}>{t('cancel')}</button><button className="danger-button" onClick={async()=>{if(!run)return;if(confirm.kind==='new'){await start(true);return;}if(confirm.kind==='sell'&&confirm.card)await saveRun(sell(run,confirm.card.uid));else{const ended=retire(run);await saveRun(ended);setScreen('game');}setConfirm(null);}}>{t(confirm.kind==='new'?'newRun':confirm.kind==='sell'?'sell':'retire')}</button></div></Dialog>}

  {screen==='game'&&run?.phase==='combat'&&combat?.choice&&<Dialog locale={locale} title={t(combat.choice.kind==='tidal'?'tidal':'choice')} wide dismissible={false} onClose={()=>{}}>{combat.choice.kind==='tidal'?<><p className="dialog-note">{t('tidalHint')}</p><TidalOptions locale={locale} onChoose={state=>{void saveRun(commitCombat(run,resolveChoice(combat,[state])));}}/></>:<><p className="dialog-note">{ui(locale,combat.choice.kind==='reorder'?'reorderHint':'chooseCount',{n:combat.choice.count,selected:choiceIds.length})}</p><div className="card-grid">{combat.choice.ids.map(id=>{const c=[...combat.hand,...combat.draw,...combat.discard,...combat.exhaust].find(c=>c.uid===id);return c?<Card key={id} card={c} locale={locale} selected={choiceIds.includes(id)} label={combat.choice?.kind==='reorder'&&choiceIds.includes(id)?String(choiceIds.indexOf(id)+1):undefined} onClick={()=>setChoiceIds(choiceIds.includes(id)?choiceIds.filter(x=>x!==id):choiceIds.length<combat.choice!.count?[...choiceIds,id]:choiceIds)} onInspect={()=>showCard(c)}/>:null;})}</div><button className="primary-button centered" disabled={choiceIds.length<(combat.choice.min??0)} onClick={()=>{void saveRun(commitCombat(run,resolveChoice(combat,choiceIds)));setChoiceIds([]);}}>{t('confirmChoice')}</button></>}</Dialog>}
  {endTidal&&combat&&<Dialog locale={locale} title={t('tidal')} wide onClose={()=>setEndTidal(false)}><p className="dialog-note">{t('tidalHint')}</p><TidalOptions locale={locale} selected={combat.tidal} onChoose={state=>void finishTurn(state)}/></Dialog>}
  {dragPoint&&combat&&<div className="card-drag-label" aria-hidden="true" style={{left:dragPoint.x,top:dragPoint.y}}>{CARDS[combat.hand.find(c=>c.uid===dragPoint.uid)?.defId??'strike'].name[locale]}</div>}
  {toast&&<div className="action-toast" role="status">{toast}<button aria-label={t('close')} onClick={()=>setToast('')}><X size={16}/></button></div>}
  {screen!=='menu'&&<footer className="status-footer"><span>{t('save')}</span><span>{run?`${t('seed')} ${run.seed}`:'HEAVENWARD'}</span></footer>}
 </main></GradeContext.Provider>;
}
